#!/usr/bin/env bash
# Regression tests for the post-session runner, queue, and one-shot finalizer.
# Bash 3.2 compatible (stock macOS).

set -u

TESTS_DIR="$(cd "$(dirname "$0")" && pwd -P)"
SKILL_DIR="$(cd "$TESTS_DIR/.." && pwd -P)"
RUNNER="$SKILL_DIR/scripts/run-specstory-session.sh"
QUEUE="$SKILL_DIR/scripts/queue-agent-commit.sh"
FINALIZER="$SKILL_DIR/scripts/finalize-agent-commit.sh"
STAGE="$SKILL_DIR/scripts/stage-agent-artifacts.sh"
CHECK_MESSAGE="$SKILL_DIR/../git-workflow/scripts/check-commit-msg.sh"
BASE="$(mktemp -d /tmp/test-post-session.XXXXXX)"
BASE="$(cd "$BASE" && pwd -P)"
FAKE_BIN="$BASE/bin"
SYSTEM_PATH="$FAKE_BIN:/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin"
UUID="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"
PASS_COUNT=0
FAIL_COUNT=0
CONTEXT_COUNT=0
LAST_RC=0
LAST_OUT=""
LAST_ERR=""
LAST_REQUEST=""

trap 'rm -rf "$BASE"' EXIT
mkdir -p "$FAKE_BIN"

printf 'bash-under-test: %s (%s)\n' "$BASH_VERSION" "$BASH"
if [ "$(uname -s)" = "Darwin" ] && [ "${BASH_VERSINFO[0]}" != "3" ]; then
  printf 'error: Darwin compatibility suite must run with /bin/bash 3.x\n' >&2
  exit 1
fi

pass() { PASS_COUNT=$((PASS_COUNT + 1)); printf '  PASS %s\n' "$1"; }
fail() { FAIL_COUNT=$((FAIL_COUNT + 1)); printf '  FAIL %s\n' "$1"; }
contains() { printf '%s\n' "$1" | grep -Fq -- "$2"; }
not_contains() { ! contains "$1" "$2"; }
file_mode() {
  python3 - "$1" <<'PY'
import os, stat, sys
print("%04o" % stat.S_IMODE(os.lstat(sys.argv[1]).st_mode))
PY
}
head_count() { git -C "$1" rev-list --count HEAD; }

cat > "$FAKE_BIN/lsof" <<'SH'
#!/usr/bin/env bash
if [ "${FAKE_LSOF_MODE:-none}" = writer ]; then
  printf '%s\n' p999999 f3 aw
  exit 0
fi
exit 1
SH
chmod +x "$FAKE_BIN/lsof"

cat > "$FAKE_BIN/gitleaks" <<'PY'
#!/usr/bin/env python3
import json
import os
import subprocess
import sys
from pathlib import Path

arguments = sys.argv[1:]
report = Path(arguments[arguments.index("--report-path") + 1])
relative = os.environ.get("FAKE_GITLEAKS_FILE", "")
secret = os.environ.get("FAKE_GITLEAKS_SECRET", "")
index_data = b""
if relative:
    process = subprocess.run(
        [os.environ.get("REAL_GIT", "git"), "show", ":" + relative],
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    if process.returncode == 0:
        index_data = process.stdout
findings = []
if relative and secret and secret.encode("utf-8") in index_data:
    findings.append(
        {
            "File": relative,
            "Secret": secret,
            "Match": secret,
            "RuleID": "fixture-rule",
            "StartLine": 8,
        }
    )
report.write_text(json.dumps(findings), encoding="utf-8")
PY
chmod +x "$FAKE_BIN/gitleaks"

cat > "$FAKE_BIN/specstory" <<'SH'
#!/usr/bin/env bash
set -u

write_session() {
  mkdir -p .specstory/history
  if [ "${TEST_INVALID_TRANSCRIPT:-0}" = "1" ]; then
    printf '\377not-a-transcript\n' > .specstory/history/session.md
  else
    printf '%s\n' \
      '<!-- Generated by SpecStory, Markdown v2.1.0 -->' \
      '' \
      '# Post-session test' \
      '' \
      "<!-- Claude Code Session $TEST_UUID (2026-09-01 00:00:00Z) -->" \
      '' \
      '_**Agent (Claude Opus 5 2026-09-01 00:00:01Z)**_' \
      > .specstory/history/session.md
  fi
  if [ -n "${TEST_SESSION_SECRET:-}" ]; then
    printf 'TOKEN=%s\n' "$TEST_SESSION_SECRET" >> .specstory/history/session.md
  fi
  if [ "${TEST_USE_PLAN:-0}" = "1" ]; then
    mkdir -p .claude/plans
    printf '# Exact plan\n' > .claude/plans/exact.md
  fi
  slug=$(printf '%s' "$PWD" | sed 's|[^A-Za-z0-9]|-|g')
  jsonl="$HOME/.claude/projects/$slug/$TEST_UUID.jsonl"
  mkdir -p "$(dirname "$jsonl")"
  python3 - "$jsonl" "$TEST_UUID" "$PWD" <<'PY'
import json, sys
with open(sys.argv[1], "w", encoding="utf-8") as stream:
    stream.write(json.dumps({"type": "user", "sessionId": sys.argv[2], "cwd": sys.argv[3]}) + "\n")
PY
}

queue_once() {
  if [ "${TEST_USE_PLAN:-0}" = "1" ]; then
    "$BASH" "$TEST_QUEUE" --commit --session-id "$TEST_UUID" \
      --specstory-path .specstory/history/session.md \
      --plan .claude/plans/exact.md --message-file message.txt
  else
    "$BASH" "$TEST_QUEUE" --commit --session-id "$TEST_UUID" \
      --specstory-path .specstory/history/session.md \
      --no-plan --message-file message.txt
  fi
}

case "${1:-}" in
  sync)
    printf '%s\n' "$*" >> "$TEST_SYNC_LOG"
    [ "${TEST_SYNC_FAIL:-0}" = "1" ] && exit 41
    exit 0 ;;
  run)
    printf '%s\n' "$*" >> "$TEST_RUN_LOG"
    [ "${2:-}" = claude ] || exit 65
    write_session
    env | LC_ALL=C grep '^AGENT_HISTORY_' | cut -d= -f1 | LC_ALL=C sort > "$TEST_CHILD_ENV_LOG" || :
    printf '%s\n' "$AGENT_HISTORY_REQUEST_PATH" > "$TEST_REQUEST_LOG"
    case "$TEST_MODE" in
      no-request) exit 0 ;;
      queue-once) queue_once; exit $? ;;
      hold)
        queue_once || exit $?
        printf 'ready\n' > "$TEST_READY_FIFO"
        IFS= read -r _release < "$TEST_RELEASE_FIFO"
        exit 0 ;;
      signal-hold)
        trap 'printf "terminated\n" > "$TEST_SIGNAL_LOG"; exit 143' TERM
        queue_once || exit $?
        printf 'ready\n' > "$TEST_READY_FIFO"
        IFS= read -r _release < "$TEST_RELEASE_FIFO"
        exit 0 ;;
      signal-zero-hold)
        trap 'printf "terminated-zero\n" > "$TEST_SIGNAL_LOG"; exit 0' TERM
        queue_once || exit $?
        printf 'ready\n' > "$TEST_READY_FIFO"
        IFS= read -r _release < "$TEST_RELEASE_FIFO"
        exit 0 ;;
      descendant-hold)
        queue_once || exit $?
        python3 - .specstory/history/session.md "$TEST_DESCENDANT_PID_LOG" <<'PY' &
import os, sys, time
with open(sys.argv[1], "ab", buffering=0):
    with open(sys.argv[2], "w", encoding="ascii") as stream:
        stream.write(str(os.getpid()) + "\n")
        stream.flush()
        os.fsync(stream.fileno())
    time.sleep(300)
PY
        while [ ! -s "$TEST_DESCENDANT_PID_LOG" ]; do sleep 0.01; done
        exit 0 ;;
      idempotent-nonzero)
        queue_once || exit $?
        queue_once || exit $?
        exit 37 ;;
      differing-request)
        queue_once || exit $?
        printf 'different body\n' >> message.txt
        queue_once
        exit $? ;;
      unsafe-selector)
        unsafe_path=$'unsafe-selector\nsecond-row.md'
        "$BASH" "$TEST_QUEUE" --commit --session-id "$TEST_UUID" \
          --specstory-path "$unsafe_path" --no-plan --message-file message.txt
        exit $? ;;
      bad-run-mode)
        chmod 0755 "$(dirname "$AGENT_HISTORY_REQUEST_PATH")"
        queue_once
        exit $? ;;
      bad-request-mode)
        queue_once || exit $?
        chmod 0644 "$AGENT_HISTORY_REQUEST_PATH"
        queue_once
        exit $? ;;
      request-symlink)
        target="$(dirname "$AGENT_HISTORY_REQUEST_PATH")/request-target"
        printf '{}\n' > "$target"
        chmod 0600 "$target"
        ln -s request-target "$AGENT_HISTORY_REQUEST_PATH"
        queue_once
        exit $? ;;
      transcript-symlink)
        mv .specstory/history/session.md .specstory/history/session-real.md
        ln -s session-real.md .specstory/history/session.md
        queue_once
        exit $? ;;
      outside-request)
        outside="$PWD/outside/$AGENT_HISTORY_RUN_ID/request.json"
        mkdir -p "$(dirname "$outside")"
        chmod 0700 "$PWD/outside" "$PWD/outside/$AGENT_HISTORY_RUN_ID"
        AGENT_HISTORY_REQUEST_PATH="$outside" queue_once
        exit $? ;;
      unsafe-message)
        printf 'feat: invalid message\rbody\n' > message.txt
        queue_once
        exit $? ;;
      *) exit 66 ;;
    esac ;;
  *) exit 64 ;;
esac
SH
chmod +x "$FAKE_BIN/specstory"

new_context() {
  CONTEXT_COUNT=$((CONTEXT_COUNT + 1))
  REPO="$BASE/repo-$CONTEXT_COUNT"
  HOME_DIR="$BASE/home-$CONTEXT_COUNT"
  OUT_FILE="$BASE/out-$CONTEXT_COUNT"
  ERR_FILE="$BASE/err-$CONTEXT_COUNT"
  REQUEST_LOG="$BASE/request-$CONTEXT_COUNT"
  SYNC_LOG="$BASE/sync-$CONTEXT_COUNT"
  RUN_LOG="$BASE/run-$CONTEXT_COUNT"
  CHILD_ENV_LOG="$BASE/env-$CONTEXT_COUNT"
  READY_FIFO="$BASE/ready-$CONTEXT_COUNT"
  RELEASE_FIFO="$BASE/release-$CONTEXT_COUNT"
  SIGNAL_LOG="$BASE/signal-$CONTEXT_COUNT"
  DESCENDANT_PID_LOG="$BASE/descendant-$CONTEXT_COUNT"
  HOOK_LOG="$BASE/hooks-$CONTEXT_COUNT"
  mkdir -p "$REPO" "$HOME_DIR"
  git -C "$REPO" init -q -b main
  git -C "$REPO" config user.name 'Lifecycle Test'
  git -C "$REPO" config user.email 'lifecycle@example.com'
  printf 'base\n' > "$REPO/feature.txt"
  git -C "$REPO" add feature.txt
  git -C "$REPO" -c core.hooksPath=/dev/null \
    -c user.name=test -c user.email=test@example.com commit -q -m init
  rm -f "$REPO/.git/COMMIT_EDITMSG"
  printf 'feat: finalize recorded session\n\nPreserve the exact post-session review trail.\n' \
    > "$REPO/message.txt"
  TEST_SESSION_SECRET=""
  FAKE_GITLEAKS_FILE=""
  FAKE_GITLEAKS_SECRET=""
  TEST_FAIL_HOOK=""
  TEST_PREPARE_MUTATION=0
  TEST_REMOVE_PROVENANCE=0
  TEST_PRE_COMMIT_READY_FIFO=""
  TEST_PRE_COMMIT_RELEASE_FIFO=""
  rm -f "$HOOK_LOG" "$DESCENDANT_PID_LOG"
  LAST_REQUEST=""
}

stage_feature() {
  printf 'changed\n' >> "$REPO/feature.txt"
  git -C "$REPO" add feature.txt
}

install_native_hooks() {
  local hook hooks_dir="${1:-$REPO/.git/hooks}"
  mkdir -p "$hooks_dir"
  cat > "$hooks_dir/agent-history-test-hook" <<'SH'
#!/usr/bin/env bash
set -u
hook="$(basename "$0")"
printf '%s\t%s\t%s\t%s\t%s\n' \
  "$hook" "$PWD" "${AGENT_HISTORY_SESSION_ID:-}" \
  "${AGENT_HISTORY_SPECSTORY_PATH:-}" \
  "${AGENT_HISTORY_PLAN:-${AGENT_HISTORY_NO_PLAN:-}}" >> "$HOOK_LOG"
if [ "$hook" = pre-commit ] && [ -n "${TEST_PRE_COMMIT_READY_FIFO:-}" ]; then
  printf 'ready\n' > "$TEST_PRE_COMMIT_READY_FIFO"
  IFS= read -r _release < "$TEST_PRE_COMMIT_RELEASE_FIFO"
fi
if [ "$hook" = prepare-commit-msg ]; then
  selector_args=(
    --session-only
    --session-id "$AGENT_HISTORY_SESSION_ID"
    --specstory-path "$AGENT_HISTORY_SPECSTORY_PATH"
  )
  if [ -n "${AGENT_HISTORY_PLAN:-}" ]; then
    selector_args+=(--plan "$AGENT_HISTORY_PLAN")
  else
    selector_args+=(--no-plan)
  fi
  "$BASH" "$TEST_STAGE" "${selector_args[@]}" --check-staged >/dev/null 2>&1 || exit $?
  if [ "${TEST_PREPARE_MUTATION:-0}" = "1" ]; then
    printf 'Hook-Prepared: immediate-owned-mutation\n' >> "$1"
  fi
elif [ "$hook" = commit-msg ]; then
  "$BASH" "$TEST_CHECK_MESSAGE" --agentic --staged --file "$1" >/dev/null 2>&1 || exit $?
  if [ "${TEST_REMOVE_PROVENANCE:-0}" = "1" ]; then
    python3 - "$1" <<'PY'
import os, sys
path = sys.argv[1]
with open(path, "rb") as stream:
    lines = stream.readlines()
with open(path, "wb") as stream:
    stream.writelines(line for line in lines if not line.startswith(b"AI-Assisted-By: "))
os.chmod(path, 0o600)
PY
  fi
fi
if [ "${TEST_FAIL_HOOK:-}" = "$hook" ]; then
  printf '%s\n' 'private hook diagnostic that must stay suppressed' >&2
  exit 42
fi
exit 0
SH
  chmod +x "$hooks_dir/agent-history-test-hook"
  for hook in pre-commit prepare-commit-msg commit-msg post-commit; do
    cp "$hooks_dir/agent-history-test-hook" "$hooks_dir/$hook"
    chmod +x "$hooks_dir/$hook"
  done
}

runner_env() {
  local fake_mode="$1"
  shift
  env \
    PATH="$SYSTEM_PATH" \
    HOME="$HOME_DIR" \
    GIT_CONFIG_GLOBAL=/dev/null \
    GIT_CONFIG_SYSTEM=/dev/null \
    AGENT_HISTORY_SECRET_SHOULD_NOT_PASS=hidden \
    AGENT_HISTORY_ALLOW_COMMIT=hidden \
    TEST_QUEUE="$QUEUE" \
    TEST_UUID="$UUID" \
    TEST_MODE="$fake_mode" \
    TEST_USE_PLAN="${TEST_USE_PLAN:-0}" \
    TEST_INVALID_TRANSCRIPT="${TEST_INVALID_TRANSCRIPT:-0}" \
    TEST_SESSION_SECRET="${TEST_SESSION_SECRET:-}" \
    TEST_SYNC_FAIL="${TEST_SYNC_FAIL:-0}" \
    FAKE_GITLEAKS_FILE="${FAKE_GITLEAKS_FILE:-}" \
    FAKE_GITLEAKS_SECRET="${FAKE_GITLEAKS_SECRET:-}" \
    REAL_GIT="${REAL_GIT:-$(command -v git)}" \
    HOOK_LOG="$HOOK_LOG" \
    TEST_STAGE="$STAGE" \
    TEST_CHECK_MESSAGE="$CHECK_MESSAGE" \
    TEST_FAIL_HOOK="${TEST_FAIL_HOOK:-}" \
    TEST_PREPARE_MUTATION="${TEST_PREPARE_MUTATION:-0}" \
    TEST_REMOVE_PROVENANCE="${TEST_REMOVE_PROVENANCE:-0}" \
    TEST_PRE_COMMIT_READY_FIFO="${TEST_PRE_COMMIT_READY_FIFO:-}" \
    TEST_PRE_COMMIT_RELEASE_FIFO="${TEST_PRE_COMMIT_RELEASE_FIFO:-}" \
    TEST_DESCENDANT_PID_LOG="$DESCENDANT_PID_LOG" \
    TEST_REQUEST_LOG="$REQUEST_LOG" \
    TEST_SYNC_LOG="$SYNC_LOG" \
    TEST_RUN_LOG="$RUN_LOG" \
    TEST_CHILD_ENV_LOG="$CHILD_ENV_LOG" \
    TEST_READY_FIFO="$READY_FIFO" \
    TEST_RELEASE_FIFO="$RELEASE_FIFO" \
    TEST_SIGNAL_LOG="$SIGNAL_LOG" \
    "$@"
}

run_runner() {
  mode="$1"
  authorization="$2"
  shift 2
  : > "$OUT_FILE"
  : > "$ERR_FILE"
  rm -f "$REQUEST_LOG" "$SYNC_LOG" "$RUN_LOG" "$CHILD_ENV_LOG" "$SIGNAL_LOG" \
    "$DESCENDANT_PID_LOG"
  set +e
  if [ "$authorization" = allow ]; then
    (cd "$REPO" && runner_env "$mode" /bin/bash "$RUNNER" --provider claude --allow-commit -- "$@") \
      > "$OUT_FILE" 2> "$ERR_FILE"
  else
    (cd "$REPO" && runner_env "$mode" /bin/bash "$RUNNER" --provider claude -- "$@") \
      > "$OUT_FILE" 2> "$ERR_FILE"
  fi
  LAST_RC=$?
  set +e
  LAST_OUT="$(<"$OUT_FILE")"
  LAST_ERR="$(<"$ERR_FILE")"
  if [ -s "$REQUEST_LOG" ]; then LAST_REQUEST="$(<"$REQUEST_LOG")"; else LAST_REQUEST=""; fi
}

run_finalizer() {
  repo="$1"
  request="$2"
  auth_kind="$3"
  auth_value="${4:-}"
  rotation_confirmed="${5:-0}"
  final_out="$BASE/final-out-$CONTEXT_COUNT"
  final_err="$BASE/final-err-$CONTEXT_COUNT"
  if [ "$auth_kind" = allow ]; then
    finalizer_command=(/bin/bash "$FINALIZER" --request "$request" --allow-commit)
  else
    finalizer_command=(/bin/bash "$FINALIZER" --request "$request" --runner-token "$auth_value")
  fi
  [ "$rotation_confirmed" = "1" ] && finalizer_command+=(--rotation-confirmed)
  set +e
  (
    cd "$repo" || exit 90
    exec env PATH="$SYSTEM_PATH" HOME="$HOME_DIR" GIT_CONFIG_GLOBAL=/dev/null \
      GIT_CONFIG_SYSTEM=/dev/null FAKE_GITLEAKS_FILE="${FAKE_GITLEAKS_FILE:-}" \
      FAKE_GITLEAKS_SECRET="${FAKE_GITLEAKS_SECRET:-}" \
      REAL_GIT="${REAL_GIT:-$(command -v git)}" HOOK_LOG="$HOOK_LOG" \
      TEST_STAGE="$STAGE" TEST_CHECK_MESSAGE="$CHECK_MESSAGE" \
      TEST_FAIL_HOOK="${TEST_FAIL_HOOK:-}" \
      TEST_PREPARE_MUTATION="${TEST_PREPARE_MUTATION:-0}" \
      TEST_REMOVE_PROVENANCE="${TEST_REMOVE_PROVENANCE:-0}" \
      TEST_PRE_COMMIT_READY_FIFO="${TEST_PRE_COMMIT_READY_FIFO:-}" \
      TEST_PRE_COMMIT_RELEASE_FIFO="${TEST_PRE_COMMIT_RELEASE_FIFO:-}" \
      "${finalizer_command[@]}"
  ) > "$final_out" 2> "$final_err"
  LAST_RC=$?
  set +e
  LAST_OUT="$(<"$final_out")"
  LAST_ERR="$(<"$final_err")"
  return "$LAST_RC"
}

make_synced_request() {
  new_context
  stage_feature
  TEST_USE_PLAN=0
  TEST_INVALID_TRANSCRIPT=0
  TEST_SYNC_FAIL=0
  run_runner queue-once noauth
  SYNCED_REPO="$REPO"
  SYNCED_REQUEST="$LAST_REQUEST"
}

printf '== post-session public interfaces ==\n'
runner_help="$(/bin/bash "$RUNNER" --help)"
queue_help="$(/bin/bash "$QUEUE" --help)"
finalizer_help="$(/bin/bash "$FINALIZER" --help)"
if contains "$runner_help" 'Usage: run-specstory-session.sh [--allow-commit] claude' && \
   contains "$runner_help" '--provider claude' && contains "$runner_help" 'foreground TTY' && \
   contains "$runner_help" '22      child process group remained live'; then
  pass "runner help is explicit and noninteractive-friendly"
else
  fail "runner help is explicit and noninteractive-friendly"
fi
if contains "$queue_help" '--commit' && contains "$queue_help" '--session-id UUID' && \
   contains "$queue_help" '--specstory-path PATH' && contains "$queue_help" '--no-plan' && \
   contains "$queue_help" '--message-file PATH'; then
  pass "queue help names every required exact input"
else
  fail "queue help names every required exact input"
fi
# Backticks are literal help text.
# shellcheck disable=SC2016
if contains "$finalizer_help" '--rotation-confirmed' && \
   contains "$finalizer_help" 'ordinary `git commit -F`' && \
   contains "$finalizer_help" 'reconciliation-only'; then
  pass "finalizer help documents one-shot commit and rotation recovery"
else
  fail "finalizer help documents one-shot commit and rotation recovery"
fi
set +e
/bin/bash "$RUNNER" --provider codex >/dev/null 2>&1
bad_provider_rc=$?
/bin/bash "$QUEUE" --commit >/dev/null 2>&1
missing_queue_rc=$?
/bin/bash "$FINALIZER" --request /tmp/request.json >/dev/null 2>&1
missing_auth_rc=$?
set +e
if [ "$bad_provider_rc" = "2" ] && [ "$missing_queue_rc" = "1" ] && \
   [ "$missing_auth_rc" = "1" ]; then
  pass "public interfaces reject unsupported or incomplete invocations"
else
  fail "public interfaces reject unsupported or incomplete invocations"
fi

printf '\n== runner lifecycle and queue boundary ==\n'
new_context
stage_feature
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=0
run_runner no-request noauth
first_run_path="$LAST_REQUEST"
run_runner no-request noauth
second_run_path="$LAST_REQUEST"
run_count="$(find "$REPO/.git/agent-history-hygiene/runs" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ')"
if [ "$LAST_RC" = "0" ] && contains "$LAST_OUT" '"status":"no_request"' && \
   [ ! -e "$first_run_path" ] && [ ! -e "$second_run_path" ] && \
   [ "$first_run_path" != "$second_run_path" ] && [ "$run_count" = "2" ] && \
   [ ! -e "$SYNC_LOG" ]; then
  pass "no-request runs are no-ops with unique private run paths"
else
  fail "no-request runs are no-ops with unique private run paths"
fi

new_context
stage_feature
TEST_USE_PLAN=1
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=0
install_native_hooks
mkfifo "$READY_FIFO" "$RELEASE_FIFO"
: > "$OUT_FILE"; : > "$ERR_FILE"
(
  cd "$REPO" || exit 90
  exec env PATH="$SYSTEM_PATH" HOME="$HOME_DIR" GIT_CONFIG_GLOBAL=/dev/null \
    GIT_CONFIG_SYSTEM=/dev/null AGENT_HISTORY_SECRET_SHOULD_NOT_PASS=hidden \
    AGENT_HISTORY_ALLOW_COMMIT=hidden TEST_QUEUE="$QUEUE" TEST_UUID="$UUID" \
    TEST_MODE=hold TEST_USE_PLAN=1 TEST_INVALID_TRANSCRIPT=0 TEST_SYNC_FAIL=0 \
    TEST_REQUEST_LOG="$REQUEST_LOG" TEST_SYNC_LOG="$SYNC_LOG" TEST_RUN_LOG="$RUN_LOG" \
    TEST_CHILD_ENV_LOG="$CHILD_ENV_LOG" TEST_READY_FIFO="$READY_FIFO" \
    TEST_RELEASE_FIFO="$RELEASE_FIFO" TEST_SIGNAL_LOG="$SIGNAL_LOG" \
    REAL_GIT="$(command -v git)" HOOK_LOG="$HOOK_LOG" TEST_STAGE="$STAGE" \
    TEST_CHECK_MESSAGE="$CHECK_MESSAGE" TEST_FAIL_HOOK='' \
    FAKE_GITLEAKS_FILE='' FAKE_GITLEAKS_SECRET='' \
    /bin/bash "$RUNNER" --provider claude --allow-commit -- --resume "$UUID"
) > "$OUT_FILE" 2> "$ERR_FILE" &
barrier_pid=$!
IFS= read -r barrier_value < "$READY_FIFO"
barrier_request="$(<"$REQUEST_LOG")"
barrier_run_dir="$(dirname "$barrier_request")"
if [ "$barrier_value" = ready ] && [ -f "$barrier_request" ] && \
   [ ! -e "$SYNC_LOG" ] && [ ! -e "$barrier_run_dir/composed-message.txt" ] && \
   [ ! -e "$REPO/.git/LAZYGIT_PENDING_COMMIT" ] && [ ! -e "$HOOK_LOG" ] && \
   [ "$(head_count "$REPO")" = "1" ]; then
  pass "no sync or finalizer occurs before fake SpecStory exits"
else
  fail "no sync or finalizer occurs before fake SpecStory exits"
fi
printf 'release\n' > "$RELEASE_FIFO"
set +e
wait "$barrier_pid"
barrier_rc=$?
set +e
barrier_out="$(<"$OUT_FILE")"
barrier_err="$(<"$ERR_FILE")"
sync_lines="$(wc -l < "$SYNC_LOG" | tr -d ' ')"
child_env_names="$(<"$CHILD_ENV_LOG")"
barrier_names="$(git -C "$REPO" show --format= --name-only HEAD)"
barrier_message="$(git -C "$REPO" show -s --format=%B HEAD)"
hook_lines="$(wc -l < "$HOOK_LOG" | tr -d ' ')"
wrong_hook_cwd="$(cut -f2 "$HOOK_LOG" | grep -Fvx "$REPO" || true)"
if [ "$barrier_rc" = "0" ] && [ "$sync_lines" = "1" ] && \
   grep -Fxq "sync claude -s $UUID --silent" "$SYNC_LOG" && \
   grep -Fxq "run claude --resume $UUID" "$RUN_LOG" && \
   contains "$barrier_out" '"status":"committed"' && \
   contains "$barrier_out" '"commit_attempted":true' && \
   contains "$barrier_err" 'status=committed' && \
   [ "$(head_count "$REPO")" = "2" ]; then
  pass "exit 0 triggers one exact sync and one ordinary commit"
else
  fail "exit 0 triggers one exact sync and one ordinary commit"
fi
if [ "$hook_lines" = "4" ] && [ -z "$wrong_hook_cwd" ] && \
   [ "$(grep -c '^pre-commit' "$HOOK_LOG")" = "1" ] && \
   [ "$(grep -c '^prepare-commit-msg' "$HOOK_LOG")" = "1" ] && \
   [ "$(grep -c '^commit-msg' "$HOOK_LOG")" = "1" ] && \
   [ "$(grep -c '^post-commit' "$HOOK_LOG")" = "1" ] && \
   [ "$(cut -f3 "$HOOK_LOG" | sort -u)" = "$UUID" ] && \
   [ "$(cut -f4 "$HOOK_LOG" | sort -u)" = '.specstory/history/session.md' ] && \
   [ "$(cut -f5 "$HOOK_LOG" | sort -u)" = '.claude/plans/exact.md' ]; then
  pass "all four native hooks run once in the original worktree with selectors"
else
  fail "all four native hooks run once in the original worktree with selectors"
fi
if contains "$barrier_names" 'feature.txt' && \
   contains "$barrier_names" '.specstory/history/session.md' && \
   contains "$barrier_names" '.claude/plans/exact.md' && \
   contains "$barrier_message" 'AI-Assisted-By: Claude Code (Claude Opus 5)' && \
   contains "$barrier_message" 'Agent-Transcript: .specstory/history/session.md' && \
   contains "$barrier_message" 'Agent-Plan: .claude/plans/exact.md' && \
   [ "$(printf '%s\n' "$barrier_message" | grep -c '^Agent-History-Request:')" = "1" ] && \
   [ ! -e "$REPO/.git/LAZYGIT_PENDING_COMMIT" ]; then
  pass "success commits the exact feature, artifacts, and canonical trailers"
else
  fail "success commits the exact feature, artifacts, and canonical trailers"
fi
if [ "$child_env_names" = $'AGENT_HISTORY_REQUEST_PATH\nAGENT_HISTORY_RUN_ID' ]; then
  pass "child receives only inert lifecycle environment"
else
  fail "child receives only inert lifecycle environment"
fi
if python3 - "$barrier_request" "$REPO" "$UUID" <<'PY'
import json, os, sys
request_path, root, session = sys.argv[1:]
with open(request_path, encoding="utf-8") as stream:
    value = json.load(stream)
assert value["schema_version"] == 1
assert value["action"] == "commit"
assert value["provider"] == "claude"
assert value["worktree_root"] == os.path.realpath(root)
assert value["git_dir"] == os.path.realpath(os.path.join(root, ".git"))
assert value["session_id"] == session
assert value["specstory_path"] == ".specstory/history/session.md"
assert value["plan_policy"] == "path"
assert value["plan_path"] == ".claude/plans/exact.md"
assert set(value) == {
    "schema_version", "request_id", "request_path", "action", "provider",
    "worktree_root", "git_dir", "head_ref", "head_oid", "index_tree",
    "session_id", "specstory_path", "plan_policy", "plan_path",
    "base_message_path", "base_message_sha256", "created_at",
}
PY
then
  pass "queue writes the strict metadata-only request schema"
else
  fail "queue writes the strict metadata-only request schema"
fi
if [ "$(file_mode "$barrier_run_dir")" = "0700" ] && \
   [ "$(file_mode "$barrier_request")" = "0600" ] && \
   [ "$(file_mode "$barrier_run_dir/base-message.txt")" = "0600" ] && \
   [ "$(file_mode "$barrier_run_dir/journal.json")" = "0600" ] && \
   [ "$(file_mode "$barrier_run_dir/composed-message.txt")" = "0600" ] && \
   cmp -s "$REPO/message.txt" "$barrier_run_dir/base-message.txt" && \
   cmp -s "$barrier_run_dir/composed-message.txt" "$REPO/.git/COMMIT_EDITMSG" && \
   ! contains "$barrier_names" 'message.txt' && [ "$(head_count "$REPO")" = "2" ]; then
  pass "private run state remains ownership-safe and outside the commit"
else
  fail "private run state remains ownership-safe and outside the commit"
fi

isolated_parent="$BASE/isolated-install"
isolated_skill="$isolated_parent/agent-history-hygiene"
mkdir -p "$isolated_parent"
cp -R "$SKILL_DIR" "$isolated_skill"
original_runner="$RUNNER"
original_queue="$QUEUE"
RUNNER="$isolated_skill/scripts/run-specstory-session.sh"
QUEUE="$isolated_skill/scripts/queue-agent-commit.sh"
new_context
stage_feature
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=0
run_runner queue-once allow
isolated_run_dir="$(dirname "$LAST_REQUEST")"
if [ "$LAST_RC" = "0" ] && contains "$LAST_OUT" '"status":"committed"' && \
   [ ! -e "$isolated_parent/git-workflow" ] && \
   [ -f "$isolated_run_dir/composed-message.txt" ] && \
   [ "$(head_count "$REPO")" = "2" ]; then
  pass "isolated skill install validates and commits without git-workflow sibling"
else
  fail "isolated skill install validates and commits without git-workflow sibling"
fi
RUNNER="$original_runner"
QUEUE="$original_queue"

new_context
stage_feature
printf '\nagent-history-request: foreign-lowercase-token\n' >> "$REPO/message.txt"
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=0
run_runner queue-once allow
if [ "$LAST_RC" = "7" ] && \
   contains "$LAST_OUT" '"status":"message_validation_failed"' && \
   [ -f "$LAST_REQUEST" ] && \
   [ ! -e "$(dirname "$LAST_REQUEST")/composed-message.txt" ] && \
   [ ! -e "$REPO/.git/LAZYGIT_PENDING_COMMIT" ] && \
   [ "$(head_count "$REPO")" = "1" ]; then
  pass "internal validator rejects case-variant managed trailer tokens"
else
  fail "internal validator rejects case-variant managed trailer tokens"
fi

new_context
stage_feature
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=1
TEST_SYNC_FAIL=0
run_runner idempotent-nonzero allow
idempotent_run_dir="$(dirname "$LAST_REQUEST")"
if [ "$LAST_RC" = "37" ] && [ -f "$LAST_REQUEST" ] && \
   contains "$LAST_OUT" '"idempotent":false' && contains "$LAST_OUT" '"idempotent":true' && \
   contains "$LAST_OUT" '"status":"child_exit_nonzero"' && [ ! -e "$SYNC_LOG" ] && \
   [ ! -e "$idempotent_run_dir/composed-message.txt" ] && \
   [ ! -e "$REPO/.git/LAZYGIT_PENDING_COMMIT" ] && [ "$(head_count "$REPO")" = "1" ]; then
  pass "identical queue is idempotent and nonzero child status is preserved"
else
  fail "identical queue is idempotent and nonzero child status is preserved"
fi
if [ -f "$LAST_REQUEST" ] && [ "$(file_mode "$LAST_REQUEST")" = "0600" ] && \
   [ "$(git -C "$REPO" diff --cached --name-only)" = "feature.txt" ]; then
  pass "queue neither parses nor stages invalid transcript bytes"
else
  fail "queue neither parses nor stages invalid transcript bytes"
fi

new_context
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=0
run_runner queue-once allow
if [ "$LAST_RC" = "5" ] && [ ! -e "$LAST_REQUEST" ] && \
   contains "$LAST_OUT" '"status":"no_staged_feature_diff"' && [ ! -e "$SYNC_LOG" ]; then
  pass "queue requires a staged non-artifact feature diff"
else
  fail "queue requires a staged non-artifact feature diff"
fi

new_context
stage_feature
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=0
run_runner unsafe-selector allow
if [ "$LAST_RC" = "4" ] && [ ! -e "$LAST_REQUEST" ] && \
   not_contains "$LAST_ERR" 'unsafe-selector' && [ ! -e "$SYNC_LOG" ]; then
  pass "unsafe control-byte selector is rejected without reflection"
else
  fail "unsafe control-byte selector is rejected without reflection"
fi

new_context
stage_feature
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=0
run_runner bad-run-mode allow
if [ "$LAST_RC" = "4" ] && [ ! -e "$LAST_REQUEST" ] && \
   contains "$LAST_OUT" '"status":"unsafe_mode"' && [ ! -e "$SYNC_LOG" ]; then
  pass "queue rejects a precreated run directory with the wrong mode"
else
  fail "queue rejects a precreated run directory with the wrong mode"
fi

new_context
stage_feature
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=0
run_runner bad-request-mode allow
if [ "$LAST_RC" = "4" ] && [ -f "$LAST_REQUEST" ] && \
   [ "$(file_mode "$LAST_REQUEST")" = "0644" ] && \
   contains "$LAST_OUT" '"status":"unsafe_mode"' && [ ! -e "$SYNC_LOG" ]; then
  pass "queue refuses an existing request with the wrong mode"
else
  fail "queue refuses an existing request with the wrong mode"
fi

new_context
stage_feature
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=0
run_runner request-symlink allow
if [ "$LAST_RC" = "4" ] && [ -L "$LAST_REQUEST" ] && \
   contains "$LAST_OUT" '"status":"unsafe_state"' && [ ! -e "$SYNC_LOG" ]; then
  pass "queue refuses a symlink request"
else
  fail "queue refuses a symlink request"
fi

new_context
stage_feature
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=0
run_runner transcript-symlink allow
if [ "$LAST_RC" = "4" ] && [ ! -e "$LAST_REQUEST" ] && \
   contains "$LAST_OUT" '"status":"invalid_path"' && [ ! -e "$SYNC_LOG" ]; then
  pass "queue refuses a symlink transcript selector without reading it"
else
  fail "queue refuses a symlink transcript selector without reading it"
fi

new_context
stage_feature
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=0
run_runner outside-request allow
if [ "$LAST_RC" = "5" ] && [ ! -e "$LAST_REQUEST" ] && \
   contains "$LAST_OUT" '"status":"request_outside_git_dir"' && [ ! -e "$SYNC_LOG" ]; then
  pass "queue refuses a request path outside the per-worktree Git directory"
else
  fail "queue refuses a request path outside the per-worktree Git directory"
fi

new_context
stage_feature
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=0
run_runner unsafe-message allow
if [ "$LAST_RC" = "4" ] && [ ! -e "$LAST_REQUEST" ] && \
   contains "$LAST_OUT" '"status":"invalid_text"' && [ ! -e "$SYNC_LOG" ]; then
  pass "queue rejects unsafe message control bytes"
else
  fail "queue rejects unsafe message control bytes"
fi

new_context
stage_feature
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=0
run_runner differing-request allow
if [ "$LAST_RC" = "5" ] && [ -f "$LAST_REQUEST" ] && \
   contains "$LAST_OUT" '"status":"request_conflict"' && [ ! -e "$SYNC_LOG" ]; then
  pass "second differing request is refused while the first is retained"
else
  fail "second differing request is refused while the first is retained"
fi

new_context
stage_feature
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=1
run_runner queue-once allow
sync_failure_run_dir="$(dirname "$LAST_REQUEST")"
if [ "$LAST_RC" = "21" ] && [ -f "$LAST_REQUEST" ] && \
   contains "$LAST_OUT" '"status":"sync_failed"' && \
   [ "$(wc -l < "$SYNC_LOG" | tr -d ' ')" = "1" ] && \
   [ ! -e "$sync_failure_run_dir/composed-message.txt" ] && \
   [ ! -e "$REPO/.git/LAZYGIT_PENDING_COMMIT" ] && [ "$(head_count "$REPO")" = "1" ]; then
  pass "failed exact sync retains request and never calls finalizer"
else
  fail "failed exact sync retains request and never calls finalizer"
fi

printf '\n== process-group quiescence ==\n'
new_context
stage_feature
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=0
run_runner descendant-hold allow
descendant_pid="$(<"$DESCENDANT_PID_LOG")"
descendant_state="$(python3 - "$(dirname "$LAST_REQUEST")/journal.json" <<'PY'
import json, sys
with open(sys.argv[1], encoding="utf-8") as stream:
    journal = json.load(stream)
print("%s:%s" % (journal["state"], journal["failure_code"]))
PY
)"
if [ "$LAST_RC" = "22" ] && [ -f "$LAST_REQUEST" ] && \
   contains "$LAST_OUT" '"status":"process_group_not_quiescent"' && \
   [ "$descendant_state" = 'failed:process_group_not_quiescent' ] && \
   kill -0 "$descendant_pid" 2>/dev/null && [ ! -e "$SYNC_LOG" ] && \
   [ ! -e "$(dirname "$LAST_REQUEST")/composed-message.txt" ] && \
   [ "$(head_count "$REPO")" = "1" ]; then
  pass "live same-group descendant blocks sync and finalization"
else
  fail "live same-group descendant blocks sync and finalization"
fi
kill -TERM "$descendant_pid" 2>/dev/null || :
descendant_wait=0
while kill -0 "$descendant_pid" 2>/dev/null && [ "$descendant_wait" -lt 100 ]; do
  sleep 0.01
  descendant_wait=$((descendant_wait + 1))
done
kill -KILL "$descendant_pid" 2>/dev/null || :

printf '\n== targeted signal forwarding ==\n'
new_context
stage_feature
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=0
mkfifo "$READY_FIFO" "$RELEASE_FIFO"
: > "$OUT_FILE"; : > "$ERR_FILE"
(
  cd "$REPO" || exit 90
  exec env PATH="$SYSTEM_PATH" HOME="$HOME_DIR" GIT_CONFIG_GLOBAL=/dev/null \
    GIT_CONFIG_SYSTEM=/dev/null TEST_QUEUE="$QUEUE" TEST_UUID="$UUID" \
    TEST_MODE=signal-hold TEST_USE_PLAN=0 TEST_INVALID_TRANSCRIPT=0 TEST_SYNC_FAIL=0 \
    TEST_REQUEST_LOG="$REQUEST_LOG" TEST_SYNC_LOG="$SYNC_LOG" TEST_RUN_LOG="$RUN_LOG" \
    TEST_CHILD_ENV_LOG="$CHILD_ENV_LOG" TEST_READY_FIFO="$READY_FIFO" \
    TEST_RELEASE_FIFO="$RELEASE_FIFO" TEST_SIGNAL_LOG="$SIGNAL_LOG" \
    /bin/bash "$RUNNER" --provider claude --allow-commit
) > "$OUT_FILE" 2> "$ERR_FILE" &
signal_runner_pid=$!
IFS= read -r signal_ready < "$READY_FIFO"
signal_request="$(<"$REQUEST_LOG")"
kill -TERM "$signal_runner_pid"
set +e
wait "$signal_runner_pid"
signal_rc=$?
set +e
signal_out="$(<"$OUT_FILE")"
if [ "$signal_ready" = ready ] && [ "$signal_rc" = "143" ] && \
   [ -f "$signal_request" ] && [ -f "$SIGNAL_LOG" ] && \
   contains "$signal_out" '"status":"child_signaled"' && \
   [ ! -e "$SYNC_LOG" ] && [ ! -e "$(dirname "$signal_request")/composed-message.txt" ] && \
   [ "$(head_count "$REPO")" = "1" ]; then
  pass "targeted TERM reaches child, preserves 143, and never finalizes"
else
  fail "targeted TERM reaches child, preserves 143, and never finalizes"
fi

new_context
stage_feature
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=0
mkfifo "$READY_FIFO" "$RELEASE_FIFO"
: > "$OUT_FILE"; : > "$ERR_FILE"
(
  cd "$REPO" || exit 90
  exec env PATH="$SYSTEM_PATH" HOME="$HOME_DIR" GIT_CONFIG_GLOBAL=/dev/null \
    GIT_CONFIG_SYSTEM=/dev/null TEST_QUEUE="$QUEUE" TEST_UUID="$UUID" \
    TEST_MODE=signal-zero-hold TEST_USE_PLAN=0 TEST_INVALID_TRANSCRIPT=0 TEST_SYNC_FAIL=0 \
    TEST_REQUEST_LOG="$REQUEST_LOG" TEST_SYNC_LOG="$SYNC_LOG" TEST_RUN_LOG="$RUN_LOG" \
    TEST_CHILD_ENV_LOG="$CHILD_ENV_LOG" TEST_READY_FIFO="$READY_FIFO" \
    TEST_RELEASE_FIFO="$RELEASE_FIFO" TEST_SIGNAL_LOG="$SIGNAL_LOG" \
    /bin/bash "$RUNNER" --provider claude --allow-commit
) > "$OUT_FILE" 2> "$ERR_FILE" &
signal_zero_runner_pid=$!
IFS= read -r signal_zero_ready < "$READY_FIFO"
signal_zero_request="$(<"$REQUEST_LOG")"
kill -TERM "$signal_zero_runner_pid"
set +e
wait "$signal_zero_runner_pid"
signal_zero_rc=$?
set +e
signal_zero_out="$(<"$OUT_FILE")"
if [ "$signal_zero_ready" = ready ] && [ "$signal_zero_rc" = "143" ] && \
   [ -f "$signal_zero_request" ] && \
   [ "$(<"$SIGNAL_LOG")" = 'terminated-zero' ] && \
   contains "$signal_zero_out" '"status":"child_signaled"' && \
   [ ! -e "$SYNC_LOG" ] && \
   [ ! -e "$(dirname "$signal_zero_request")/composed-message.txt" ] && \
   [ "$(head_count "$REPO")" = "1" ]; then
  pass "forwarded TERM remains interrupting when child trap exits zero"
else
  fail "forwarded TERM remains interrupting when child trap exits zero"
fi

printf '\n== finalizer authorization, stale state, and draft ownership ==\n'
make_synced_request
repo="$SYNCED_REPO"; request="$SYNCED_REQUEST"; run_dir="$(dirname "$request")"
if [ "$LAST_RC" = "0" ] && contains "$LAST_OUT" '"status":"authorization_required"' && \
   [ -f "$request" ] && [ ! -e "$repo/.git/LAZYGIT_PENDING_COMMIT" ] && \
   [ "$(wc -l < "$SYNC_LOG" | tr -d ' ')" = "1" ]; then
  pass "runner without parent authorization syncs but does not finalize"
else
  fail "runner without parent authorization syncs but does not finalize"
fi
run_finalizer "$repo" "$request" token wrong-token
if [ "$LAST_RC" = "5" ] && contains "$LAST_OUT" '"status":"invalid_authorization"' && \
   [ ! -e "$repo/.git/LAZYGIT_PENDING_COMMIT" ]; then
  pass "request file alone and wrong parent token cannot authorize finalization"
else
  fail "request file alone and wrong parent token cannot authorize finalization"
fi

printf 'foreign lazy draft\n' > "$repo/.git/LAZYGIT_PENDING_COMMIT"
foreign_lazy_before="$(<"$repo/.git/LAZYGIT_PENDING_COMMIT")"
run_finalizer "$repo" "$request" allow
if [ "$LAST_RC" = "9" ] && contains "$LAST_OUT" '"status":"draft_conflict"' && \
   [ "$(<"$repo/.git/LAZYGIT_PENDING_COMMIT")" = "$foreign_lazy_before" ] && \
   [ ! -e "$repo/.git/COMMIT_EDITMSG" ] && [ -f "$run_dir/composed-message.txt" ]; then
  pass "foreign LazyGit draft is preserved without partial handoff"
else
  fail "foreign LazyGit draft is preserved without partial handoff"
fi
rm -f "$repo/.git/LAZYGIT_PENDING_COMMIT"
printf 'foreign edit draft\n' > "$repo/.git/COMMIT_EDITMSG"
foreign_edit_before="$(<"$repo/.git/COMMIT_EDITMSG")"
run_finalizer "$repo" "$request" allow
if [ "$LAST_RC" = "9" ] && contains "$LAST_OUT" '"status":"draft_conflict"' && \
   [ "$(<"$repo/.git/COMMIT_EDITMSG")" = "$foreign_edit_before" ] && \
   [ ! -e "$repo/.git/LAZYGIT_PENDING_COMMIT" ]; then
  pass "foreign COMMIT_EDITMSG is preserved without partial handoff"
else
  fail "foreign COMMIT_EDITMSG is preserved without partial handoff"
fi
rm -f "$repo/.git/COMMIT_EDITMSG"
install_native_hooks
TEST_FAIL_HOOK=pre-commit
: > "$HOOK_LOG"
run_finalizer "$repo" "$request" allow
hook_failure_rc="$LAST_RC"
hook_failure_out="$LAST_OUT"
hook_failure_err="$LAST_ERR"
hook_failure_message="$(<"$run_dir/composed-message.txt")"
hook_failure_state="$(python3 - "$run_dir/journal.json" <<'PY'
import json, sys
with open(sys.argv[1], encoding="utf-8") as stream:
    print(json.load(stream)["state"])
PY
)"
if [ "$hook_failure_rc" = "11" ] && \
   contains "$hook_failure_out" '"status":"commit_failed"' && \
   not_contains "$hook_failure_out$hook_failure_err" 'private hook diagnostic' && \
   [ "$hook_failure_state" = prepared ] && [ "$(head_count "$repo")" = "1" ] && \
   [ "$(wc -l < "$HOOK_LOG" | tr -d ' ')" = "1" ] && \
   [ "$(grep -c '^pre-commit' "$HOOK_LOG")" = "1" ] && \
   cmp -s "$run_dir/composed-message.txt" "$repo/.git/LAZYGIT_PENDING_COMMIT" && \
   cmp -s "$run_dir/composed-message.txt" "$repo/.git/COMMIT_EDITMSG" && \
   [ "$(file_mode "$repo/.git/LAZYGIT_PENDING_COMMIT")" = "0600" ] && \
   [ "$(file_mode "$repo/.git/COMMIT_EDITMSG")" = "0600" ] && \
   contains "$hook_failure_message" 'AI-Assisted-By: Claude Code (Claude Opus 5)' && \
   contains "$hook_failure_message" 'Agent-Transcript: .specstory/history/session.md' && \
   contains "$hook_failure_message" 'Agent-History-Request:'; then
  pass "hook failure retains full private drafts and one prepared snapshot"
else
  fail "hook failure retains full private drafts and one prepared snapshot"
fi
printf 'user-edited draft\n' > "$repo/.git/LAZYGIT_PENDING_COMMIT"
run_finalizer "$repo" "$request" allow
if [ "$LAST_RC" = "9" ] && contains "$LAST_OUT" '"status":"draft_conflict"' && \
   [ "$(<"$repo/.git/LAZYGIT_PENDING_COMMIT")" = 'user-edited draft' ] && \
   [ "$(wc -l < "$HOOK_LOG" | tr -d ' ')" = "1" ]; then
  pass "edited owned draft is preserved without a commit retry"
else
  fail "edited owned draft is preserved without a commit retry"
fi
TEST_FAIL_HOOK=""

# Git normally leaves the previous successful commit message in COMMIT_EDITMSG.
# That exact stale scratch is safe to replace after the no-operation guard; an
# unrelated value remains covered by the foreign-draft refusal above.
make_synced_request
scratch_repo="$SYNCED_REPO"; scratch_request="$SYNCED_REQUEST"
scratch_run_dir="$(dirname "$scratch_request")"
python3 - "$scratch_repo" "$scratch_repo/.git/COMMIT_EDITMSG" <<'PY'
import os, subprocess, sys
root, output = sys.argv[1:]
raw = subprocess.check_output(["git", "-C", root, "cat-file", "commit", "HEAD"])
headers, separator, message = raw.partition(b"\n\n")
assert headers and separator and message
with open(output, "wb") as stream:
    stream.write(message)
os.chmod(output, 0o644)
PY
run_finalizer "$scratch_repo" "$scratch_request" allow
if [ "$LAST_RC" = "0" ] && contains "$LAST_OUT" '"status":"committed"' && \
   [ "$(head_count "$scratch_repo")" = "2" ] && \
   cmp -s "$scratch_run_dir/composed-message.txt" "$scratch_repo/.git/COMMIT_EDITMSG" && \
   [ ! -e "$scratch_repo/.git/LAZYGIT_PENDING_COMMIT" ]; then
  pass "prior-HEAD COMMIT_EDITMSG scratch is safely replaced"
else
  fail "prior-HEAD COMMIT_EDITMSG scratch is safely replaced"
fi

make_synced_request
stale_repo="$SYNCED_REPO"; stale_request="$SYNCED_REQUEST"
printf 'later staged change\n' >> "$stale_repo/feature.txt"
git -C "$stale_repo" add feature.txt
run_finalizer "$stale_repo" "$stale_request" allow
if [ "$LAST_RC" = "6" ] && contains "$LAST_OUT" '"status":"stale_state"' && \
   [ ! -e "$stale_repo/.git/LAZYGIT_PENDING_COMMIT" ] && [ "$(head_count "$stale_repo")" = "1" ]; then
  pass "changed staged tree makes the queued request stale"
else
  fail "changed staged tree makes the queued request stale"
fi

make_synced_request
ref_repo="$SYNCED_REPO"; ref_request="$SYNCED_REQUEST"
git -C "$ref_repo" checkout -q -b moved-after-queue
run_finalizer "$ref_repo" "$ref_request" allow
if [ "$LAST_RC" = "6" ] && contains "$LAST_OUT" '"status":"stale_state"' && \
   [ ! -e "$ref_repo/.git/LAZYGIT_PENDING_COMMIT" ]; then
  pass "changed branch ref makes the queued request stale"
else
  fail "changed branch ref makes the queued request stale"
fi

make_synced_request
operation_repo="$SYNCED_REPO"; operation_request="$SYNCED_REQUEST"
printf '%s\n' "$(git -C "$operation_repo" rev-parse HEAD)" > "$operation_repo/.git/MERGE_HEAD"
run_finalizer "$operation_repo" "$operation_request" allow
if [ "$LAST_RC" = "6" ] && contains "$LAST_OUT" '"status":"git_operation_in_progress"' && \
   [ ! -e "$operation_repo/.git/LAZYGIT_PENDING_COMMIT" ]; then
  pass "in-progress Git operation blocks finalization"
else
  fail "in-progress Git operation blocks finalization"
fi
rm -f "$operation_repo/.git/MERGE_HEAD"

make_synced_request
rebase_residue_repo="$SYNCED_REPO"; rebase_residue_request="$SYNCED_REQUEST"
printf '%s\n' "$(git -C "$rebase_residue_repo" rev-parse HEAD)" \
  > "$rebase_residue_repo/.git/REBASE_HEAD"
run_finalizer "$rebase_residue_repo" "$rebase_residue_request" allow
if [ "$LAST_RC" = "0" ] && contains "$LAST_OUT" '"status":"committed"' && \
   [ "$(head_count "$rebase_residue_repo")" = "2" ]; then
  pass "stale REBASE_HEAD alone does not impersonate an active rebase"
else
  fail "stale REBASE_HEAD alone does not impersonate an active rebase"
fi
rm -f "$rebase_residue_repo/.git/REBASE_HEAD"

make_synced_request
selector_repo="$SYNCED_REPO"; selector_request="$SYNCED_REQUEST"
printf '# replaced without exact prologue\n' > "$selector_repo/.specstory/history/session.md"
run_finalizer "$selector_repo" "$selector_request" allow
if [ "$LAST_RC" = "7" ] && contains "$LAST_OUT" '"status":"exact_selector_failed"' && \
   [ ! -e "$selector_repo/.git/LAZYGIT_PENDING_COMMIT" ]; then
  pass "finalizer revalidates exact session after sync"
else
  fail "finalizer revalidates exact session after sync"
fi

make_synced_request
writer_repo="$SYNCED_REPO"; writer_request="$SYNCED_REQUEST"
FAKE_LSOF_MODE=writer run_finalizer "$writer_repo" "$writer_request" allow
if [ "$LAST_RC" = "7" ] && contains "$LAST_OUT" '"status":"active_writer"' && \
   [ ! -e "$writer_repo/.git/LAZYGIT_PENDING_COMMIT" ] && \
   [ ! -e "$(dirname "$writer_request")/composed-message.txt" ] && \
   [ "$(git -C "$writer_repo" diff --cached --name-only)" = feature.txt ]; then
  pass "active writer blocks before artifact staging"
else
  fail "active writer blocks before artifact staging"
fi
unset FAKE_LSOF_MODE

printf '\n== frozen commit index and hook integrity ==\n'
make_synced_request
freeze_repo="$SYNCED_REPO"; freeze_request="$SYNCED_REQUEST"
printf 'concurrent staged content\n' > "$freeze_repo/concurrent.txt"
install_native_hooks
freeze_ready="$BASE/freeze-ready-$CONTEXT_COUNT"
freeze_release="$BASE/freeze-release-$CONTEXT_COUNT"
mkfifo "$freeze_ready" "$freeze_release"
TEST_PRE_COMMIT_READY_FIFO="$freeze_ready"
TEST_PRE_COMMIT_RELEASE_FIFO="$freeze_release"
state_order_bin="$BASE/state-order-bin-$CONTEXT_COUNT"
state_order_log="$BASE/state-order-$CONTEXT_COUNT"
state_order_journal="$(dirname "$freeze_request")/journal.json"
mkdir -p "$state_order_bin"
cat > "$state_order_bin/git" <<'SH'
#!/usr/bin/env bash
is_frozen_write_tree=0
case "${GIT_INDEX_FILE:-}" in
  *index.agent-history-commit.*)
    for argument in "$@"; do
      [ "$argument" = write-tree ] && is_frozen_write_tree=1
    done ;;
esac
if [ "$is_frozen_write_tree" = "1" ] && [ ! -e "$STATE_ORDER_LOG" ]; then
  python3 - "$STATE_ORDER_JOURNAL" "$STATE_ORDER_LOG" <<'PY'
import json, sys
with open(sys.argv[1], encoding="utf-8") as stream:
    state = json.load(stream)["state"]
with open(sys.argv[2], "w", encoding="ascii") as stream:
    stream.write(state + "\n")
PY
fi
exec "$REAL_GIT" "$@"
SH
chmod +x "$state_order_bin/git"
freeze_original_system_path="$SYSTEM_PATH"
freeze_original_real_git="${REAL_GIT:-}"
REAL_GIT="$(command -v git)"
SYSTEM_PATH="$state_order_bin:$SYSTEM_PATH"
STATE_ORDER_LOG="$state_order_log"
STATE_ORDER_JOURNAL="$state_order_journal"
export REAL_GIT STATE_ORDER_LOG STATE_ORDER_JOURNAL
: > "$HOOK_LOG"
run_finalizer "$freeze_repo" "$freeze_request" allow &
freeze_finalizer_pid=$!
IFS= read -r freeze_barrier < "$freeze_ready"
git -C "$freeze_repo" add concurrent.txt
freeze_add_rc=$?
printf 'release\n' > "$freeze_release"
set +e
wait "$freeze_finalizer_pid"
freeze_rc=$?
set +e
freeze_out="$(<"$BASE/final-out-$CONTEXT_COUNT")"
freeze_state_during_copy="$(<"$state_order_log")"
SYSTEM_PATH="$freeze_original_system_path"
REAL_GIT="$freeze_original_real_git"
unset STATE_ORDER_LOG STATE_ORDER_JOURNAL
TEST_PRE_COMMIT_READY_FIFO=""
TEST_PRE_COMMIT_RELEASE_FIFO=""
freeze_commit_names="$(git -C "$freeze_repo" show --format= --name-only HEAD)"
freeze_staged_names="$(git -C "$freeze_repo" diff --cached --name-only)"
freeze_temp_count="$(find "$freeze_repo/.git" -maxdepth 1 -type f \
  -name 'index.agent-history-commit.*' | wc -l | tr -d ' ')"
if [ "$freeze_state_during_copy" = prepared ]; then
  pass "journal stays prepared until the frozen commit index is verified"
else
  fail "journal stays prepared until the frozen commit index is verified"
fi
if [ "$freeze_barrier" = ready ] && [ "$freeze_add_rc" = "0" ] && \
   [ "$freeze_rc" = "0" ] && contains "$freeze_out" '"status":"committed"' && \
   not_contains "$freeze_commit_names" 'concurrent.txt' && \
   contains "$freeze_commit_names" 'feature.txt' && \
   [ "$freeze_staged_names" = 'concurrent.txt' ] && \
   [ "$(wc -l < "$HOOK_LOG" | tr -d ' ')" = "4" ] && \
   [ "$freeze_temp_count" = "0" ] && [ "$(head_count "$freeze_repo")" = "2" ]; then
  pass "frozen commit index excludes and preserves concurrent canonical staging"
else
  fail "frozen commit index excludes and preserves concurrent canonical staging"
fi

make_synced_request
config_repo="$SYNCED_REPO"; config_request="$SYNCED_REQUEST"
config_hooks="$config_repo/.git/configured-hooks"
install_native_hooks "$config_hooks"
git -C "$config_repo" config --local core.hooksPath "$config_hooks"
: > "$HOOK_LOG"
GIT_CONFIG_COUNT=1
GIT_CONFIG_KEY_0=core.hooksPath
GIT_CONFIG_VALUE_0=/dev/null
# Git requires its own quoted parameter encoding.
# shellcheck disable=SC2089
GIT_CONFIG_PARAMETERS="'core.hooksPath'='/dev/null'"
# Preserve the literal encoding for Git.
# shellcheck disable=SC2090
export GIT_CONFIG_COUNT GIT_CONFIG_KEY_0 GIT_CONFIG_VALUE_0 GIT_CONFIG_PARAMETERS
run_finalizer "$config_repo" "$config_request" allow
config_rc="$LAST_RC"
config_out="$LAST_OUT"
unset GIT_CONFIG_COUNT GIT_CONFIG_KEY_0 GIT_CONFIG_VALUE_0 GIT_CONFIG_PARAMETERS
if [ "$config_rc" = "0" ] && contains "$config_out" '"status":"committed"' && \
   [ "$(wc -l < "$HOOK_LOG" | tr -d ' ')" = "4" ] && \
   [ "$(grep -c '^pre-commit' "$HOOK_LOG")" = "1" ] && \
   [ "$(grep -c '^prepare-commit-msg' "$HOOK_LOG")" = "1" ] && \
   [ "$(grep -c '^commit-msg' "$HOOK_LOG")" = "1" ] && \
   [ "$(grep -c '^post-commit' "$HOOK_LOG")" = "1" ]; then
  pass "commit environment rejects hook-path config injection and honors local hooks"
else
  fail "commit environment rejects hook-path config injection and honors local hooks"
fi

make_synced_request
proof_repo="$SYNCED_REPO"; proof_request="$SYNCED_REQUEST"
proof_journal="$(dirname "$proof_request")/journal.json"
install_native_hooks
TEST_REMOVE_PROVENANCE=1
: > "$HOOK_LOG"
run_finalizer "$proof_repo" "$proof_request" allow
proof_rc="$LAST_RC"
proof_out="$LAST_OUT"
TEST_REMOVE_PROVENANCE=0
proof_message="$(git -C "$proof_repo" show -s --format=%B HEAD)"
proof_state="$(python3 - "$proof_journal" <<'PY'
import json, sys
with open(sys.argv[1], encoding="utf-8") as stream:
    journal = json.load(stream)
print("%s:%s" % (journal["state"], journal["failure_code"]))
PY
)"
if [ "$proof_rc" = "8" ] && \
   contains "$proof_out" '"status":"commit_recovery_required"' && \
   not_contains "$proof_out" '"status":"committed"' && \
   [ "$proof_state" = 'committing:commit_outcome_unproven' ] && \
   not_contains "$proof_message" 'AI-Assisted-By:' && \
   contains "$proof_message" 'Agent-Transcript: .specstory/history/session.md' && \
   [ "$(wc -l < "$HOOK_LOG" | tr -d ' ')" = "4" ] && \
   [ "$(head_count "$proof_repo")" = "2" ]; then
  pass "post-commit proof rejects a hook-stripped provenance message"
else
  fail "post-commit proof rejects a hook-stripped provenance message"
fi

make_synced_request
adopt_repo="$SYNCED_REPO"; adopt_request="$SYNCED_REQUEST"
adopt_run_dir="$(dirname "$adopt_request")"
adopt_journal="$adopt_run_dir/journal.json"
adopt_saved="$BASE/adopted-editmsg-$CONTEXT_COUNT"
install_native_hooks
TEST_PREPARE_MUTATION=1
TEST_FAIL_HOOK=commit-msg
: > "$HOOK_LOG"
run_finalizer "$adopt_repo" "$adopt_request" allow
adopt_failure_rc="$LAST_RC"
cp "$adopt_repo/.git/COMMIT_EDITMSG" "$adopt_saved"
adopt_digest_matches="$(python3 - "$adopt_journal" "$adopt_saved" <<'PY'
import hashlib, json, sys
with open(sys.argv[1], encoding="utf-8") as stream:
    journal = json.load(stream)
with open(sys.argv[2], "rb") as stream:
    digest = hashlib.sha256(stream.read()).hexdigest()
print("yes" if journal["state"] == "prepared" and journal["commit_editmsg_draft_sha256"] == digest else "no")
PY
)"
printf 'user edit after failed commit\n' > "$adopt_repo/.git/COMMIT_EDITMSG"
TEST_PREPARE_MUTATION=0
TEST_FAIL_HOOK=""
run_finalizer "$adopt_repo" "$adopt_request" allow
adopt_conflict_rc="$LAST_RC"
adopt_conflict_out="$LAST_OUT"
adopt_hooks_after_conflict="$(wc -l < "$HOOK_LOG" | tr -d ' ')"
cp "$adopt_saved" "$adopt_repo/.git/COMMIT_EDITMSG"
chmod 0600 "$adopt_repo/.git/COMMIT_EDITMSG"
run_finalizer "$adopt_repo" "$adopt_request" allow
adopt_recovery_rc="$LAST_RC"
adopt_recovery_out="$LAST_OUT"
adopt_message="$(git -C "$adopt_repo" show -s --format=%B HEAD)"
if [ "$adopt_failure_rc" = "11" ] && [ "$adopt_digest_matches" = yes ] && \
   [ "$adopt_conflict_rc" = "9" ] && \
   contains "$adopt_conflict_out" '"status":"draft_conflict"' && \
   [ "$adopt_hooks_after_conflict" = "3" ] && \
   [ "$adopt_recovery_rc" = "0" ] && \
   contains "$adopt_recovery_out" '"status":"committed"' && \
   not_contains "$adopt_message" 'Hook-Prepared:' && \
   contains "$adopt_message" 'AI-Assisted-By:' && \
   [ "$(wc -l < "$HOOK_LOG" | tr -d ' ')" = "7" ] && \
   [ "$(head_count "$adopt_repo")" = "2" ]; then
  pass "failed-hook draft adoption permits only unchanged explicit recovery"
else
  fail "failed-hook draft adoption permits only unchanged explicit recovery"
fi

printf '\n== sanitizer rotation stop and confirmed recovery ==\n'
new_context
stage_feature
TEST_USE_PLAN=0
TEST_INVALID_TRANSCRIPT=0
TEST_SYNC_FAIL=0
rotation_secret='fixture-credential-that-requires-rotation'
TEST_SESSION_SECRET="$rotation_secret"
FAKE_GITLEAKS_FILE='.specstory/history/session.md'
FAKE_GITLEAKS_SECRET="$rotation_secret"
install_native_hooks
rotation_git_bin="$BASE/rotation-git-bin"
rotation_add_log="$BASE/rotation-add-log"
mkdir -p "$rotation_git_bin"
cat > "$rotation_git_bin/git" <<'SH'
#!/usr/bin/env bash
if [ "${1:-}" = add ]; then
  dry=0
  for argument in "$@"; do [ "$argument" = --dry-run ] && dry=1; done
  [ "$dry" = "1" ] || printf '%s\n' add >> "$ROTATION_ADD_LOG"
fi
exec "$REAL_GIT" "$@"
SH
chmod +x "$rotation_git_bin/git"
: > "$rotation_add_log"
original_system_path="$SYSTEM_PATH"
REAL_GIT="$(command -v git)"
SYSTEM_PATH="$rotation_git_bin:$SYSTEM_PATH"
ROTATION_ADD_LOG="$rotation_add_log"
export ROTATION_ADD_LOG
run_runner queue-once allow
rotation_repo="$REPO"
rotation_request="$LAST_REQUEST"
rotation_run_dir="$(dirname "$rotation_request")"
rotation_index="$(git -C "$rotation_repo" show :.specstory/history/session.md)"
rotation_worktree="$(<"$rotation_repo/.specstory/history/session.md")"
rotation_message="$(<"$rotation_run_dir/composed-message.txt")"
rotation_state="$(python3 - "$rotation_run_dir/journal.json" <<'PY'
import json, sys
with open(sys.argv[1], encoding="utf-8") as stream:
    journal = json.load(stream)
assert journal["staging_ready"] is True
assert journal["message_ready"] is True
assert journal["expected_commit_parent"]
assert journal["expected_commit_tree"]
print(journal["state"])
PY
)"
if [ "$LAST_RC" = "10" ] && \
   contains "$LAST_OUT" '"status":"rotation_required"' && \
   contains "$LAST_OUT" '"commit_attempted":false' && \
   not_contains "$LAST_OUT$LAST_ERR" "$rotation_secret" && \
   [ "$rotation_state" = rotation_required ] && \
   [ "$(head_count "$rotation_repo")" = "1" ] && [ ! -e "$HOOK_LOG" ] && \
   [ "$(wc -l < "$rotation_add_log" | tr -d ' ')" = "1" ] && \
   contains "$rotation_index" '[REDACTED:fixture-rule]' && \
   contains "$rotation_worktree" '[REDACTED:fixture-rule]' && \
   ! contains "$rotation_index" "$rotation_secret" && \
   ! contains "$rotation_worktree" "$rotation_secret" && \
   cmp -s "$rotation_run_dir/composed-message.txt" \
     "$rotation_repo/.git/LAZYGIT_PENDING_COMMIT" && \
   cmp -s "$rotation_run_dir/composed-message.txt" \
     "$rotation_repo/.git/COMMIT_EDITMSG" && \
   contains "$rotation_message" 'AI-Assisted-By: Claude Code (Claude Opus 5)' && \
   contains "$rotation_message" 'Agent-History-Request:'; then
  pass "sanitized index and worktree stop in rotation-required state before commit"
else
  fail "sanitized index and worktree stop in rotation-required state before commit"
fi

run_finalizer "$rotation_repo" "$rotation_request" allow
unconfirmed_rc="$LAST_RC"
unconfirmed_out="$LAST_OUT"
unconfirmed_adds="$(wc -l < "$rotation_add_log" | tr -d ' ')"
run_finalizer "$rotation_repo" "$rotation_request" allow '' 1
confirmed_rc="$LAST_RC"
confirmed_out="$LAST_OUT"
confirmed_adds="$(wc -l < "$rotation_add_log" | tr -d ' ')"
rotation_commit_message="$(git -C "$rotation_repo" show -s --format=%B HEAD)"
if [ "$unconfirmed_rc" = "10" ] && \
   contains "$unconfirmed_out" '"status":"rotation_confirmation_required"' && \
   [ "$confirmed_rc" = "0" ] && contains "$confirmed_out" '"status":"committed"' && \
   [ "$unconfirmed_adds" = "1" ] && [ "$confirmed_adds" = "1" ] && \
   [ "$(head_count "$rotation_repo")" = "2" ] && \
   [ "$(wc -l < "$HOOK_LOG" | tr -d ' ')" = "4" ] && \
   [ "$(printf '%s\n' "$rotation_commit_message" | \
      grep -c '^Agent-History-Request:')" = "1" ] && \
   [ ! -e "$rotation_repo/.git/LAZYGIT_PENDING_COMMIT" ]; then
  pass "explicit rotation confirmation resumes prepared tree once without restaging"
else
  fail "explicit rotation confirmation resumes prepared tree once without restaging"
fi
SYSTEM_PATH="$original_system_path"
unset ROTATION_ADD_LOG
REAL_GIT=""
TEST_SESSION_SECRET=""
FAKE_GITLEAKS_FILE=""
FAKE_GITLEAKS_SECRET=""

printf '\n== request isolation and durable journal refusal ==\n'
make_synced_request
mode_repo="$SYNCED_REPO"; mode_request="$SYNCED_REQUEST"; mode_run_dir="$(dirname "$mode_request")"
chmod 0644 "$mode_request"
run_finalizer "$mode_repo" "$mode_request" allow
wrong_request_mode_rc="$LAST_RC"
chmod 0600 "$mode_request"
chmod 0755 "$mode_run_dir"
run_finalizer "$mode_repo" "$mode_request" allow
wrong_run_mode_rc="$LAST_RC"
chmod 0700 "$mode_run_dir"
if [ "$wrong_request_mode_rc" = "4" ] && [ "$wrong_run_mode_rc" = "4" ]; then
  pass "finalizer rejects wrong request and run-directory modes"
else
  fail "finalizer rejects wrong request and run-directory modes"
fi
mv "$mode_request" "$mode_run_dir/request.saved"
ln -s request.saved "$mode_request"
run_finalizer "$mode_repo" "$mode_request" allow
symlink_request_rc="$LAST_RC"
rm -f "$mode_request"
mv "$mode_run_dir/request.saved" "$mode_request"
if [ "$symlink_request_rc" = "4" ]; then
  pass "finalizer refuses a symlink request"
else
  fail "finalizer refuses a symlink request"
fi

linked="$BASE/linked-worktree"
git -C "$mode_repo" worktree add -q -b linked-test "$linked"
linked_git_dir="$(git -C "$linked" rev-parse --absolute-git-dir)"
run_finalizer "$linked" "$mode_request" allow
if [ "$LAST_RC" = "5" ] && contains "$LAST_OUT" '"status":"request_outside_git_dir"' && \
   [ ! -e "$linked_git_dir/LAZYGIT_PENDING_COMMIT" ] && [ "$(head_count "$mode_repo")" = "1" ]; then
  pass "linked worktree cannot consume another worktree's request"
else
  fail "linked worktree cannot consume another worktree's request"
fi

make_synced_request
strict_repo="$SYNCED_REPO"; strict_request="$SYNCED_REQUEST"
python3 - "$strict_request" <<'PY'
import json, os, sys
path = sys.argv[1]
with open(path, encoding="utf-8") as stream:
    value = json.load(stream)
value["unexpected"] = True
temporary = path + ".tmp"
with open(temporary, "w", encoding="utf-8", newline="\n") as stream:
    stream.write(json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n")
os.chmod(temporary, 0o600)
os.replace(temporary, path)
PY
run_finalizer "$strict_repo" "$strict_request" allow
if [ "$LAST_RC" = "4" ] && contains "$LAST_OUT" '"status":"invalid_request"' && \
   [ ! -e "$strict_repo/.git/LAZYGIT_PENDING_COMMIT" ]; then
  pass "strict request parser rejects unknown keys without evaluation"
else
  fail "strict request parser rejects unknown keys without evaluation"
fi

make_synced_request
recovery_repo="$SYNCED_REPO"; recovery_request="$SYNCED_REQUEST"
recovery_journal="$(dirname "$recovery_request")/journal.json"
install_native_hooks
TEST_FAIL_HOOK=pre-commit
: > "$HOOK_LOG"
run_finalizer "$recovery_repo" "$recovery_request" allow
prepared_recovery_rc="$LAST_RC"
TEST_FAIL_HOOK=""
python3 - "$recovery_journal" <<'PY'
import json, os, sys
journal_path = sys.argv[1]
with open(journal_path, encoding="utf-8") as stream:
    journal = json.load(stream)
assert journal["state"] == "prepared"
journal["state"] = "committing"
journal["commit_oid"] = None
journal["failure_code"] = "simulated_uncertain_return"
temporary = journal_path + ".tmp"
with open(temporary, "w", encoding="utf-8", newline="\n") as stream:
    stream.write(json.dumps(journal, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n")
os.chmod(temporary, 0o600)
os.replace(temporary, journal_path)
PY
run_finalizer "$recovery_repo" "$recovery_request" allow
if [ "$prepared_recovery_rc" = "11" ] && [ "$LAST_RC" = "8" ] && \
   contains "$LAST_OUT" '"status":"commit_recovery_unproven"' && \
   [ "$(head_count "$recovery_repo")" = "1" ] && \
   [ "$(wc -l < "$HOOK_LOG" | tr -d ' ')" = "1" ] && \
   [ -f "$recovery_repo/.git/LAZYGIT_PENDING_COMMIT" ]; then
  pass "uncertain committing journal reconciles only and never retries"
else
  fail "uncertain committing journal reconciles only and never retries"
fi

make_synced_request
outside_repo="$SYNCED_REPO"; outside_request="$SYNCED_REQUEST"
outside_run_id="$(basename "$(dirname "$outside_request")")"
outside_path="$BASE/outside-runs/$outside_run_id/request.json"
run_finalizer "$outside_repo" "$outside_path" allow
if [ "$LAST_RC" = "5" ] && contains "$LAST_OUT" '"status":"request_outside_git_dir"' && \
   [ ! -e "$outside_repo/.git/LAZYGIT_PENDING_COMMIT" ]; then
  pass "request path outside the per-worktree Git directory is refused"
else
  fail "request path outside the per-worktree Git directory is refused"
fi

printf '\npass: %d\nfail: %d\n' "$PASS_COUNT" "$FAIL_COUNT"
[ "$FAIL_COUNT" = "0" ]
