#!/usr/bin/env bash
# Regression tests for scripts/agent-commit-metadata.sh.

set -u

TESTS_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILL_DIR="$(cd "$TESTS_DIR/.." && pwd)"
SCRIPT="$SKILL_DIR/scripts/agent-commit-metadata.sh"
PASS_COUNT=0
FAIL_COUNT=0

pass() { PASS_COUNT=$((PASS_COUNT + 1)); printf '  PASS %s\n' "$1"; }
fail() { FAIL_COUNT=$((FAIL_COUNT + 1)); printf '  FAIL %s\n' "$1"; }

make_repo() {
  local repo
  repo=$(mktemp -d /tmp/test-agent-metadata.XXXXXX)
  git -C "$repo" init -q -b main
  git -C "$repo" -c core.hooksPath=/dev/null -c user.name=test -c user.email=test@example.com \
    commit -q --allow-empty -m init
  printf '%s' "$repo"
}

write_codex_transcript() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  printf '%s\n' \
    '<!-- Generated by SpecStory, Markdown v2.1.0 -->' \
    '<!-- Codex CLI Session abc (2026-08-27 06:27:27Z) -->' \
    '_**Agent (gpt-5.6-sol 2026-08-27 06:27:38Z)**_' \
    '_**Agent (gpt-5.6-sol 2026-08-27 06:28:38Z)**_' \
    > "$path"
}

write_claude_transcript() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  printf '%s\n' \
    '<!-- Claude Code Session def (2026-08-27 06:27:27Z) -->' \
    '_**Agent (Claude Fable 5 2026-08-27 06:27:38Z)**_' \
    '_**Agent (Claude Opus 5 (1M context) 2026-08-27 06:28:38Z)**_' \
    > "$path"
}

printf '== agent commit metadata ==\n'

repo=$(make_repo)
write_codex_transcript "$repo/.specstory/history/session.md"
mkdir -p "$repo/.claude/plans"
printf '# Plan\n' > "$repo/.claude/plans/plan one.md"
git -C "$repo" add .specstory/history/session.md ".claude/plans/plan one.md"
out=$(cd "$repo" && bash "$SCRIPT" 2>/dev/null)
if printf '%s\n' "$out" | grep -Fxq 'AI-Assisted-By: Codex CLI (gpt-5.6-sol)' && \
   [ "$(printf '%s\n' "$out" | grep -c '^AI-Assisted-By:')" = "1" ] && \
   printf '%s\n' "$out" | grep -Fxq 'Agent-Transcript: .specstory/history/session.md' && \
   printf '%s\n' "$out" | grep -Fxq 'Agent-Plan: .claude/plans/plan one.md'; then
  pass "parse staged Codex transcript, dedupe model, preserve spaced plan path"
else
  fail "parse staged Codex transcript"
fi

json=$(cd "$repo" && bash "$SCRIPT" --format json 2>/dev/null)
if printf '%s' "$json" | grep -Fq '"assistants":["Codex CLI (gpt-5.6-sol)"]'; then
  pass "emit JSON"
else
  fail "emit JSON"
fi
rm -rf "$repo"

repo=$(make_repo)
write_claude_transcript "$repo/.specstory/history/session.md"
git -C "$repo" add .specstory/history/session.md
out=$(cd "$repo" && bash "$SCRIPT" 2>/dev/null)
if [ "$(printf '%s\n' "$out" | grep -c '^AI-Assisted-By:')" = "2" ] && \
   printf '%s\n' "$out" | grep -Fxq 'AI-Assisted-By: Claude Code (Claude Fable 5)' && \
   printf '%s\n' "$out" | grep -Fxq 'AI-Assisted-By: Claude Code (Claude Opus 5 (1M context))'; then
  pass "preserve distinct models from one staged session"
else
  fail "preserve distinct models from one staged session"
fi
rm -rf "$repo"

# Exercise the helper itself with the stock interpreter and a PATH that cannot
# resolve a newer Homebrew Bash. This covers Bash 3.2's empty-array + `set -u`
# behavior in both trailer and JSON output.
repo=$(make_repo)
write_codex_transcript "$repo/.specstory/history/transcript-only.md"
git -C "$repo" add .specstory/history/transcript-only.md
metadata_err="$repo/metadata.err"
out=$(cd "$repo" && PATH=/usr/bin:/bin /bin/bash "$SCRIPT" 2>"$metadata_err")
rc=$?
json=$(cd "$repo" && PATH=/usr/bin:/bin /bin/bash "$SCRIPT" --format json 2>>"$metadata_err")
json_rc=$?
expected_trailers=$(printf '%s\n' \
  'AI-Assisted-By: Codex CLI (gpt-5.6-sol)' \
  'Agent-Transcript: .specstory/history/transcript-only.md')
expected_json='{"assistants":["Codex CLI (gpt-5.6-sol)"],"transcripts":[".specstory/history/transcript-only.md"],"plans":[]}'
if [ "$rc" = "0" ] && [ "$json_rc" = "0" ] && \
   [ "$out" = "$expected_trailers" ] && [ "$json" = "$expected_json" ]; then
  pass "stock Bash transcript-only metadata omits an empty plan collection"
else
  fail "stock Bash transcript-only metadata (trailers rc=$rc, JSON rc=$json_rc)"
fi
rm -rf "$repo"

repo=$(make_repo)
for plan in \
  .claude/plans/claude.md \
  .cursor/plans/cursor.md \
  .opencode/plans/opencode.md \
  .specify/specify.md \
  .codex/codex.md; do
  mkdir -p "$(dirname "$repo/$plan")"
  printf '# Plan\n' > "$repo/$plan"
done
mkdir -p "$repo/.cursor/rules"
printf '# Rule\n' > "$repo/.cursor/rules/not-a-plan.mdc"
git -C "$repo" add .claude/plans/claude.md .cursor/plans/cursor.md \
  .opencode/plans/opencode.md .specify/specify.md .codex/codex.md \
  .cursor/rules/not-a-plan.mdc
(cd "$repo" && PATH=/usr/bin:/bin /bin/bash "$SCRIPT" >/dev/null 2>&1)
rc=$?
if [ "$rc" = "4" ]; then pass "require explicit identity without transcript"
else fail "require explicit identity without transcript (got $rc)"; fi

out=$(cd "$repo" && PATH=/usr/bin:/bin /bin/bash "$SCRIPT" \
  --harness Cursor --model claude-4.6 2>/dev/null)
rc=$?
expected_trailers=$(printf '%s\n' \
  'AI-Assisted-By: Cursor (claude-4.6)' \
  'Agent-Plan: .claude/plans/claude.md' \
  'Agent-Plan: .codex/codex.md' \
  'Agent-Plan: .cursor/plans/cursor.md' \
  'Agent-Plan: .opencode/plans/opencode.md' \
  'Agent-Plan: .specify/specify.md')
if [ "$rc" = "0" ] && [ "$out" = "$expected_trailers" ]; then
  pass "classify only declared plan roots; Cursor rules remain non-plan artifacts"
else
  fail "classify declared plan roots without Cursor rules (got $rc)"
fi
rm -rf "$repo"

repo=$(make_repo)
git -C "$repo" config core.hooksPath .githooks
(cd "$repo" && bash "$SKILL_DIR/scripts/bootstrap-project.sh" --install-hook --dry-run >/dev/null 2>&1)
rc=$?
if [ "$rc" = "6" ] && [ ! -e "$repo/.pre-commit-config.yaml" ]; then
  pass "bootstrap rejects inactive repo hook before writing files"
else
  fail "bootstrap rejects inactive repo hook before writing files (got $rc)"
fi
rm -rf "$repo"

repo=$(make_repo)
(cd "$repo" && bash "$SCRIPT" >/dev/null 2>&1)
rc=$?
if [ "$rc" = "3" ]; then pass "no staged artifacts → exit 3"
else fail "no staged artifacts → exit 3 (got $rc)"; fi
rm -rf "$repo"

printf 'pass: %d\nfail: %d\n' "$PASS_COUNT" "$FAIL_COUNT"
[ "$FAIL_COUNT" = "0" ]
