#!/usr/bin/env bash
# Regression tests for scripts/stage-agent-artifacts.sh and the installed hook.
# Bash 3.2 compatible (stock macOS).

set -u

TESTS_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILL_DIR="$(cd "$TESTS_DIR/.." && pwd)"
STAGE="$SKILL_DIR/scripts/stage-agent-artifacts.sh"
REDACTOR="$SKILL_DIR/assets/redact_secrets.py"
METADATA="$SKILL_DIR/scripts/agent-commit-metadata.sh"
BOOTSTRAP="$SKILL_DIR/scripts/bootstrap-project.sh"
BASE="$(mktemp -d /tmp/test-stage-agent.XXXXXX)"
BASE="$(cd "$BASE" && pwd -P)"
FAKE_HOME="$BASE/home"
SYSTEM_PATH="/bin:/usr/bin:$PATH"
PASS_COUNT=0
FAIL_COUNT=0
LAST_RC=0
LAST_ERR=""
STAGE_PATH=""

trap 'rm -rf "$BASE"' EXIT

printf 'bash-under-test: %s (%s)\n' "$BASH_VERSION" "$BASH"
if [ "$(uname -s)" = "Darwin" ] && [ "${BASH_VERSINFO[0]}" != "3" ]; then
  printf 'error: Darwin compatibility suite must run with /bin/bash 3.x\n' >&2
  exit 1
fi

pass() { PASS_COUNT=$((PASS_COUNT + 1)); printf '  PASS %s\n' "$1"; }
fail() { FAIL_COUNT=$((FAIL_COUNT + 1)); printf '  FAIL %s\n' "$1"; }
contains() { printf '%s\n' "$1" | grep -Fq -- "$2"; }

make_repo() {
  local name="$1" repo="$BASE/$1"
  mkdir -p "$repo"
  git -C "$repo" init -q -b main
  printf '%s\n' base > "$repo/feature.txt"
  git -C "$repo" add feature.txt
  git -C "$repo" -c core.hooksPath=/dev/null \
    -c user.name=test -c user.email=test@example.com commit -q -m init
  printf '%s' "$repo"
}

project_slug() {
  printf '%s' "$1" | sed 's|[^A-Za-z0-9]|-|g'
}

write_jsonl() {
  local repo="$1" uuid="$2" path
  path="$FAKE_HOME/.claude/projects/$(project_slug "$repo")/$uuid.jsonl"
  mkdir -p "$(dirname "$path")"
  python3 - "$path" "$uuid" "$repo" <<'PY'
import json
import sys

path, session_id, cwd = sys.argv[1:]
with open(path, "w", encoding="utf-8") as stream:
    stream.write(json.dumps({"type": "user", "sessionId": session_id, "cwd": cwd}) + "\n")
PY
}

write_transcript() {
  local repo="$1" name="$2" uuid="$3" path
  path="$repo/.specstory/history/$name"
  mkdir -p "$(dirname "$path")"
  printf '%s\n' \
    '<!-- Generated by SpecStory, Markdown v2.1.0 -->' \
    '' \
    '# 2026-08-28 08:00:00Z' \
    '' \
    "<!-- Claude Code Session $uuid (2026-08-28 08:00:00Z) -->" \
    '' \
    '_**Agent (Claude Opus 5 2026-08-28 08:00:01Z)**_' \
    > "$path"
  printf '%s' "$path"
}

write_plan() {
  local repo="$1" name="$2" path
  path="$repo/.claude/plans/$name"
  mkdir -p "$(dirname "$path")"
  printf '# Exact plan\n' > "$path"
  printf '%s' "$path"
}

run_stage() {
  local cwd="$1"
  shift
  local out="$BASE/stage-out" err="$BASE/stage-err"
  (cd "$cwd" && HOME="$FAKE_HOME" PATH="${STAGE_PATH:-$PATH}" \
    "$BASH" "$STAGE" "$@") >"$out" 2>"$err"
  LAST_RC=$?
  LAST_ERR="$(<"$err")"
}

staged_names() { git -C "$1" diff --cached --name-only; }
staged_count() { staged_names "$1" | grep -c .; }

SANITIZE_BIN="$BASE/sanitize-bin"
mkdir -p "$SANITIZE_BIN"
cat > "$SANITIZE_BIN/gitleaks" <<'PY'
#!/usr/bin/env python3
import json
import os
import subprocess
import sys
from pathlib import Path

args = sys.argv[1:]
report = Path(args[args.index("--report-path") + 1])
state_path = os.environ.get("FAKE_GITLEAKS_STATE")
call_number = 1
if state_path:
    state = Path(state_path)
    if state.exists():
        call_number = int(state.read_text(encoding="ascii")) + 1
    state.write_text(str(call_number), encoding="ascii")

relative = os.environ.get("FAKE_GITLEAKS_FILE", "")
secret = os.environ.get("FAKE_GITLEAKS_SECRET", "")
index_data = b""
if relative:
    process = subprocess.run(
        [os.environ.get("REAL_GIT", "git"), "show", ":" + relative],
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    if process.returncode == 0:
        index_data = process.stdout

if (
    os.environ.get("FAKE_GITLEAKS_MUTATE_ON_CALL") == str(call_number)
    and relative
):
    with open(relative, "ab") as stream:
        stream.write(b"writer-generation-changed\n")

findings = []
secret_bytes = secret.encode("utf-8")
if relative and secret_bytes and secret_bytes in index_data:
    findings.append(
        {
            "File": relative,
            "Secret": secret,
            "Match": secret,
            "RuleID": "fixture-rule",
            "StartLine": 7,
        }
    )
report.write_text(json.dumps(findings), encoding="utf-8")
PY
chmod +x "$SANITIZE_BIN/gitleaks"

UUID_A="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"
UUID_B="bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb"
UUID_C="cccccccc-cccc-4ccc-8ccc-cccccccccccc"

printf '== stage-agent-artifacts exact transaction ==\n'

# Exact session + explicit plan stages only the selected pair. Unrelated dirty
# artifacts remain unstaged, and metadata sees only the exact staged artifacts.
repo="$(make_repo 'exact paths with spaces')"
printf '%s\n' changed >> "$repo/feature.txt"
git -C "$repo" add feature.txt
transcript="$(write_transcript "$repo" 'selected session.md' "$UUID_A")"
write_transcript "$repo" 'unrelated session.md' "$UUID_B" >/dev/null
plan="$(write_plan "$repo" 'selected plan.md')"
write_plan "$repo" 'unrelated plan.md' >/dev/null
write_jsonl "$repo" "$UUID_A"
mkdir -p "$repo/nested/path"
run_stage "$repo/nested/path" --session-only --session-id "$UUID_A" \
  --specstory-path '.specstory/history/selected session.md' \
  --plan '.claude/plans/selected plan.md'
names="$(staged_names "$repo")"
if [ "$LAST_RC" = "0" ] && [ "$(staged_count "$repo")" = "3" ] && \
   contains "$names" '.specstory/history/selected session.md' && \
   contains "$names" '.claude/plans/selected plan.md' && \
   ! contains "$names" 'unrelated'; then
  pass "exact session stages only selected spaced transcript and plan"
else
  fail "exact session stages only selected spaced transcript and plan"
fi
metadata="$(cd "$repo" && "$BASH" "$METADATA" 2>/dev/null)"
if contains "$metadata" 'AI-Assisted-By: Claude Code (Claude Opus 5)' && \
   contains "$metadata" 'Agent-Transcript: .specstory/history/selected session.md' && \
   contains "$metadata" 'Agent-Plan: .claude/plans/selected plan.md' && \
   ! contains "$metadata" 'unrelated'; then
  pass "metadata trailers reflect only exact staged artifacts"
else
  fail "metadata trailers reflect only exact staged artifacts"
fi
[ -f "$transcript" ] && [ -f "$plan" ] || fail "exact fixture files remain present"

# --no-plan is explicit and stages only the exact transcript.
repo_no_plan="$(make_repo 'explicit no plan')"
printf '%s\n' changed >> "$repo_no_plan/feature.txt"
git -C "$repo_no_plan" add feature.txt
write_transcript "$repo_no_plan" 'session.md' "$UUID_B" >/dev/null
write_jsonl "$repo_no_plan" "$UUID_B"
run_stage "$repo_no_plan" --session-only --session-id "$UUID_B" --no-plan
names="$(staged_names "$repo_no_plan")"
if [ "$LAST_RC" = "0" ] && [ "$(staged_count "$repo_no_plan")" = "2" ] && \
   contains "$names" '.specstory/history/session.md'; then
  pass "explicit --no-plan stages only exact transcript"
else
  fail "explicit --no-plan stages only exact transcript"
fi

# Missing plan policy is a usage failure and leaves the index untouched.
repo_missing="$(make_repo 'missing plan policy')"
printf '%s\n' changed >> "$repo_missing/feature.txt"
git -C "$repo_missing" add feature.txt
write_transcript "$repo_missing" 'session.md' "$UUID_C" >/dev/null
write_jsonl "$repo_missing" "$UUID_C"
before_tree="$(git -C "$repo_missing" write-tree)"
run_stage "$repo_missing" --session-only --session-id "$UUID_C"
after_tree="$(git -C "$repo_missing" write-tree)"
if [ "$LAST_RC" = "1" ] && [ "$before_tree" = "$after_tree" ]; then
  pass "missing --plan/--no-plan fails before index mutation"
else
  fail "missing --plan/--no-plan fails before index mutation"
fi

run_stage "$repo_missing" --session-only --session-id= --no-plan
empty_session_rc="$LAST_RC"
run_stage "$repo_missing" --session-only --specstory-path= --no-plan
empty_specstory_rc="$LAST_RC"
run_stage "$repo_missing" --session-only --session-id "$UUID_C" --plan=
empty_plan_rc="$LAST_RC"
run_stage "$repo_missing" --session-only --session-id "$UUID_C" --no-plan --dirs-file=
empty_dirs_rc="$LAST_RC"
if [ "$empty_session_rc" = "1" ] && [ "$empty_specstory_rc" = "1" ] && \
   [ "$empty_plan_rc" = "1" ] && [ "$empty_dirs_rc" = "1" ]; then
  pass "empty-valued staging selectors are argument errors"
else
  fail "empty-valued staging selectors are argument errors"
fi

unsafe_selector=$'unsafe-selector\nrow'
run_stage "$repo_missing" --session-only --specstory-path "$unsafe_selector" --no-plan
unsafe_spec_rc="$LAST_RC"; unsafe_spec_err="$LAST_ERR"
run_stage "$repo_missing" --session-only --session-id "$UUID_C" --plan "$unsafe_selector"
unsafe_plan_rc="$LAST_RC"; unsafe_plan_err="$LAST_ERR"
if [ "$unsafe_spec_rc" = "1" ] && [ "$unsafe_plan_rc" = "1" ] && \
   ! contains "$unsafe_spec_err" 'unsafe-selector' && ! contains "$unsafe_plan_err" 'unsafe-selector'; then
  pass "unsafe raw staging selectors are rejected without reflection"
else
  fail "unsafe raw staging selectors are rejected without reflection"
fi

# --no-specstory still proves the exact raw session and stages no artifact when
# --no-plan is also explicit.
repo_raw="$(make_repo 'raw session only')"
printf '%s\n' changed >> "$repo_raw/feature.txt"
git -C "$repo_raw" add feature.txt
write_transcript "$repo_raw" 'left dirty.md' "$UUID_A" >/dev/null
write_jsonl "$repo_raw" "$UUID_A"
run_stage "$repo_raw" --session-only --session-id "$UUID_A" --no-specstory --no-plan
if [ "$LAST_RC" = "0" ] && [ "$(staged_count "$repo_raw")" = "1" ] && \
   contains "$LAST_ERR" 'No agent artifacts to stage'; then
  pass "explicit --no-specstory/--no-plan validates raw identity without staging"
else
  fail "explicit --no-specstory/--no-plan validates raw identity without staging"
fi

# Duplicate UUID is a selector failure. A pre-existing staged code change must
# remain byte-for-byte identical in the index.
repo_atomic="$(make_repo 'atomic selector failure')"
printf '%s\n' staged-change >> "$repo_atomic/feature.txt"
git -C "$repo_atomic" add feature.txt
write_transcript "$repo_atomic" 'alias one.md' "$UUID_B" >/dev/null
write_transcript "$repo_atomic" 'alias two.md' "$UUID_B" >/dev/null
write_plan "$repo_atomic" 'plan.md' >/dev/null
write_jsonl "$repo_atomic" "$UUID_B"
before_tree="$(git -C "$repo_atomic" write-tree)"
run_stage "$repo_atomic" --session-only --session-id "$UUID_B" --plan '.claude/plans/plan.md'
after_tree="$(git -C "$repo_atomic" write-tree)"
if [ "$LAST_RC" = "5" ] && [ "$before_tree" = "$after_tree" ] && \
   contains "$LAST_ERR" $'status\tambiguous'; then
  pass "selector ambiguity maps to exit 5 with index unchanged"
else
  fail "selector ambiguity maps to exit 5 with index unchanged"
fi

# Even a real Markdown file is rejected as a plan when it lives outside the
# checkout; the already-staged code tree remains unchanged.
outside_plan="$BASE/outside plan.md"
printf '# Outside\n' > "$outside_plan"
run_stage "$repo_atomic" --session-only --session-id "$UUID_B" \
  --specstory-path '.specstory/history/alias one.md' --plan "$outside_plan"
if [ "$LAST_RC" = "5" ] && [ "$(git -C "$repo_atomic" write-tree)" = "$before_tree" ]; then
  pass "outside plan fails validation before atomic git add"
else
  fail "outside plan fails validation before atomic git add"
fi

# Merely dirty code is not a feature diff in the next commit. The exact
# transcript must remain unstaged when no non-artifact code is in the index.
repo_guard="$(make_repo 'staged feature guard')"
printf '%s\n' changed >> "$repo_guard/feature.txt"
write_transcript "$repo_guard" 'session.md' "$UUID_C" >/dev/null
write_jsonl "$repo_guard" "$UUID_C"
before_tree="$(git -C "$repo_guard" write-tree)"
run_stage "$repo_guard" --session-only --session-id "$UUID_C" --no-plan
if [ "$LAST_RC" = "4" ] && [ "$(git -C "$repo_guard" write-tree)" = "$before_tree" ] && \
   contains "$LAST_ERR" 'no non-artifact code changes are staged'; then
  pass "unstaged working-tree code cannot satisfy the feature-diff guard"
else
  fail "unstaged working-tree code cannot satisfy the feature-diff guard"
fi

# An ignored later plan must be detected before one git add can stage the earlier
# transcript. The already-staged feature tree remains byte-identical.
repo_ignored="$(make_repo 'ignored exact plan')"
printf '%s\n' changed >> "$repo_ignored/feature.txt"
git -C "$repo_ignored" add feature.txt
write_transcript "$repo_ignored" 'session.md' "$UUID_A" >/dev/null
write_jsonl "$repo_ignored" "$UUID_A"
mkdir -p "$repo_ignored/.claude/plans"
printf '%s\n' '.claude/plans/ignored.md' > "$repo_ignored/.gitignore"
printf '# ignored\n' > "$repo_ignored/.claude/plans/ignored.md"
before_tree="$(git -C "$repo_ignored" write-tree)"
run_stage "$repo_ignored" --session-only --session-id "$UUID_A" \
  --plan '.claude/plans/ignored.md'
ignored_index="$(HOME="$FAKE_HOME" git -C "$repo_ignored" rev-parse --git-path index)"
case "$ignored_index" in /*) ;; *) ignored_index="$repo_ignored/$ignored_index" ;; esac
ignored_temp="$(find "$(dirname "$ignored_index")" -maxdepth 1 -name "$(basename "$ignored_index").agent-history.*" -print -quit)"
if [ "$LAST_RC" = "5" ] && [ "$(git -C "$repo_ignored" write-tree)" = "$before_tree" ] && \
   contains "$LAST_ERR" 'ignored and cannot be staged safely' && \
   [ ! -e "$ignored_index.lock" ] && [ -z "$ignored_temp" ]; then
  pass "batch ignore preflight prevents partial exact staging"
else
  fail "batch ignore preflight prevents partial exact staging"
fi

# Exact plans use the configured artifact directories as their source of truth.
repo_custom="$(make_repo 'custom exact plan directory')"
printf '%s\n' changed >> "$repo_custom/feature.txt"
git -C "$repo_custom" add feature.txt
write_transcript "$repo_custom" 'session.md' "$UUID_B" >/dev/null
write_jsonl "$repo_custom" "$UUID_B"
mkdir -p "$repo_custom/custom-agent/plans"
printf '# custom plan\n' > "$repo_custom/custom-agent/plans/plan.md"
printf '%s\n' '.specstory/history/' 'custom-agent/plans/' > "$repo_custom/custom-dirs.txt"
run_stage "$repo_custom" --session-only --session-id "$UUID_B" \
  --plan 'custom-agent/plans/plan.md' --dirs-file "$repo_custom/custom-dirs.txt"
names="$(staged_names "$repo_custom")"
if [ "$LAST_RC" = "0" ] && contains "$names" '.specstory/history/session.md' && \
   contains "$names" 'custom-agent/plans/plan.md'; then
  pass "trailing-slash custom dirs-file authorizes an exact plan"
else
  fail "trailing-slash custom dirs-file authorizes an exact plan"
fi

printf '\n== exact index sanitation and materialization ==\n'

# Mutation mode is never allowed to target the canonical index or an alias of
# it. Check mode remains valid for both the canonical index and a Git-style
# temporary index.
repo_index_guard="$(make_repo 'redactor alternate index guard')"
write_plan "$repo_index_guard" 'guard.md' >/dev/null
git -C "$repo_index_guard" add .claude/plans/guard.md
index_guard_tree="$(git -C "$repo_index_guard" write-tree)"
(
  cd "$repo_index_guard" || exit 90
  PATH="$SANITIZE_BIN:$SYSTEM_PATH" python3 "$REDACTOR" \
    --fix-index --files .claude/plans/guard.md
) >"$BASE/index-guard-out" 2>"$BASE/index-guard-err"
canonical_fix_rc=$?
(
  cd "$repo_index_guard" || exit 90
  PATH="$SANITIZE_BIN:$SYSTEM_PATH" python3 "$REDACTOR" --check-index
) >/dev/null 2>&1
canonical_check_rc=$?
alternate_guard="$BASE/guard-index"
cp "$repo_index_guard/.git/index" "$alternate_guard"
(
  cd "$repo_index_guard" || exit 90
  PATH="$SANITIZE_BIN:$SYSTEM_PATH" GIT_INDEX_FILE="$alternate_guard" \
    python3 "$REDACTOR" --check-index
) >/dev/null 2>&1
alternate_check_rc=$?
hardlink_guard="$BASE/guard-index-hardlink"
ln "$repo_index_guard/.git/index" "$hardlink_guard"
(
  cd "$repo_index_guard" || exit 90
  PATH="$SANITIZE_BIN:$SYSTEM_PATH" GIT_INDEX_FILE="$hardlink_guard" \
    python3 "$REDACTOR" --fix-index --files .claude/plans/guard.md
) >/dev/null 2>&1
hardlink_fix_rc=$?
if [ "$canonical_fix_rc" = "2" ] && [ "$canonical_check_rc" = "0" ] && \
   [ "$alternate_check_rc" = "0" ] && [ "$hardlink_fix_rc" = "2" ] && \
   [ "$(git -C "$repo_index_guard" write-tree)" = "$index_guard_tree" ]; then
  pass "fix-index requires a noncanonical regular alternate index"
else
  fail "fix-index requires a noncanonical regular alternate index"
fi

# Security flags are exact-session-only and cannot be smuggled into check or
# dry-run modes. Materialization never stands alone.
flag_tree="$(git -C "$repo_index_guard" write-tree)"
run_stage "$repo_index_guard" --sanitize-index
sanitize_broad_rc=$LAST_RC
run_stage "$repo_index_guard" --session-only --session-id "$UUID_A" --no-plan \
  --sanitize-index --dry-run
sanitize_dry_rc=$LAST_RC
run_stage "$repo_index_guard" --session-only --session-id "$UUID_A" --no-plan \
  --sanitize-index --check-staged
sanitize_check_rc=$LAST_RC
run_stage "$repo_index_guard" --session-only --session-id "$UUID_A" --no-plan \
  --materialize-sanitized
materialize_alone_rc=$LAST_RC
if [ "$sanitize_broad_rc" = "1" ] && [ "$sanitize_dry_rc" = "1" ] && \
   [ "$sanitize_check_rc" = "1" ] && [ "$materialize_alone_rc" = "1" ] && \
   [ "$(git -C "$repo_index_guard" write-tree)" = "$flag_tree" ]; then
  pass "sanitize and materialize flags reject incompatible modes"
else
  fail "sanitize and materialize flags reject incompatible modes"
fi
"$BASH" "$STAGE" --help > "$BASE/stage-help" 2>/dev/null
stage_help_rc=$?
stage_help="$(tr '\n' ' ' < "$BASE/stage-help")"
if [ "$stage_help_rc" = "0" ] && contains "$stage_help" 'finalizer/quiescence-only' && \
   contains "$stage_help" 'cannot stop an arbitrary live writer'; then
  pass "sanitize help requires a proven-quiescent finalizer boundary"
else
  fail "sanitize help requires a proven-quiescent finalizer boundary"
fi

# A clean exact set publishes normally and leaves the selected worktree bytes
# equal to the staged blob.
repo_sanitize_clean="$(make_repo 'sanitize clean exact set')"
printf '%s\n' changed >> "$repo_sanitize_clean/feature.txt"
git -C "$repo_sanitize_clean" add feature.txt
write_transcript "$repo_sanitize_clean" 'session.md' "$UUID_A" >/dev/null
write_jsonl "$repo_sanitize_clean" "$UUID_A"
STAGE_PATH="$SANITIZE_BIN:$SYSTEM_PATH"
unset FAKE_GITLEAKS_FILE FAKE_GITLEAKS_SECRET FAKE_GITLEAKS_STATE \
  FAKE_GITLEAKS_MUTATE_ON_CALL
run_stage "$repo_sanitize_clean" --session-only --session-id "$UUID_A" --no-plan \
  --sanitize-index --materialize-sanitized
git -C "$repo_sanitize_clean" show :.specstory/history/session.md > "$BASE/clean-index.md"
if [ "$LAST_RC" = "0" ] && \
   cmp -s "$repo_sanitize_clean/.specstory/history/session.md" "$BASE/clean-index.md"; then
  pass "clean exact sanitation publishes without replacement status"
else
  fail "clean exact sanitation publishes without replacement status"
fi

# A writer append during an otherwise clean sanitizer pass must still fail the
# late live-generation proof. Zero replacement bytes are not permission to skip
# materialization-mode validation or publish the alternate index.
repo_clean_generation="$(make_repo 'clean scan generation change')"
printf '%s\n' changed >> "$repo_clean_generation/feature.txt"
git -C "$repo_clean_generation" add feature.txt
write_transcript "$repo_clean_generation" 'session.md' "$UUID_A" >/dev/null
write_jsonl "$repo_clean_generation" "$UUID_A"
clean_generation_tree="$(git -C "$repo_clean_generation" write-tree)"
export FAKE_GITLEAKS_FILE='.specstory/history/session.md'
unset FAKE_GITLEAKS_SECRET
export FAKE_GITLEAKS_STATE="$BASE/clean-generation-scanner-state"
export FAKE_GITLEAKS_MUTATE_ON_CALL=2
STAGE_PATH="$SANITIZE_BIN:$SYSTEM_PATH"
run_stage "$repo_clean_generation" --session-only --session-id "$UUID_A" --no-plan \
  --sanitize-index --materialize-sanitized
clean_generation_content="$(<"$repo_clean_generation/.specstory/history/session.md")"
clean_generation_backups="$(find "$repo_clean_generation/.specstory/history" -maxdepth 1 \
  -name '.agent-history-backup.*' -print -quit)"
if [ "$LAST_RC" = "5" ] && \
   [ "$(git -C "$repo_clean_generation" write-tree)" = "$clean_generation_tree" ] && \
   ! git -C "$repo_clean_generation" ls-files --error-unmatch -- \
     .specstory/history/session.md >/dev/null 2>&1 && \
   contains "$clean_generation_content" 'writer-generation-changed' && \
   [ -z "$clean_generation_backups" ]; then
  pass "clean sanitizer pass still rejects a changed live generation"
else
  fail "clean sanitizer pass still rejects a changed live generation"
fi
unset FAKE_GITLEAKS_FILE FAKE_GITLEAKS_STATE FAKE_GITLEAKS_MUTATE_ON_CALL

# One actual add seeds the alternate index. The sanitizer updates blobs and
# checkout-index materializes them; no second add may read the live path.
repo_sanitize="$(make_repo 'sanitize exact secret')"
printf '%s\n' changed >> "$repo_sanitize/feature.txt"
git -C "$repo_sanitize" add feature.txt
write_transcript "$repo_sanitize" 'session.md' "$UUID_B" >/dev/null
write_jsonl "$repo_sanitize" "$UUID_B"
sanitize_secret='fixture-sensitive-value-for-index-redaction'
printf 'TOKEN=%s\n' "$sanitize_secret" >> "$repo_sanitize/.specstory/history/session.md"
count_bin="$BASE/count-add-bin"
mkdir -p "$count_bin"
cat > "$count_bin/git" <<'SH'
#!/usr/bin/env bash
if [ "${1:-}" = add ]; then
  dry=0
  for argument in "$@"; do [ "$argument" = --dry-run ] && dry=1; done
  [ "$dry" = "1" ] || printf '%s\n' add >> "$GIT_ADD_LOG"
fi
exec "$REAL_GIT" "$@"
SH
chmod +x "$count_bin/git"
: > "$BASE/git-add-log"
REAL_GIT="$(command -v git)"
export REAL_GIT
export GIT_ADD_LOG="$BASE/git-add-log"
export FAKE_GITLEAKS_FILE='.specstory/history/session.md'
export FAKE_GITLEAKS_SECRET="$sanitize_secret"
unset FAKE_GITLEAKS_STATE FAKE_GITLEAKS_MUTATE_ON_CALL
STAGE_PATH="$count_bin:$SANITIZE_BIN:$SYSTEM_PATH"
run_stage "$repo_sanitize" --session-only --session-id "$UUID_B" --no-plan \
  --sanitize-index --materialize-sanitized
sanitize_names="$(staged_names "$repo_sanitize")"
sanitize_index="$(git -C "$repo_sanitize" show :.specstory/history/session.md)"
sanitize_worktree="$(<"$repo_sanitize/.specstory/history/session.md")"
add_count="$(wc -l < "$BASE/git-add-log" | tr -d ' ')"
if [ "$LAST_RC" = "10" ] && [ "$add_count" = "1" ] && \
   contains "$sanitize_names" 'feature.txt' && \
   contains "$sanitize_names" '.specstory/history/session.md' && \
   contains "$sanitize_index" '[REDACTED:fixture-rule]' && \
   contains "$sanitize_worktree" '[REDACTED:fixture-rule]' && \
   ! contains "$sanitize_index" "$sanitize_secret" && \
   ! contains "$sanitize_worktree" "$sanitize_secret" && \
   ! contains "$LAST_ERR" "$sanitize_secret"; then
  pass "sanitizer publishes and materializes after exactly one candidate add"
else
  fail "sanitizer publishes and materializes after exactly one candidate add"
fi

# A writer generation change after the one add is detected against the
# filter-aware pre-sanitize OID before any checkout. The candidate is discarded
# and the real feature-only index remains byte-identical.
repo_generation="$(make_repo 'generation changes during sanitize')"
printf '%s\n' changed >> "$repo_generation/feature.txt"
git -C "$repo_generation" add feature.txt
write_transcript "$repo_generation" 'session.md' "$UUID_C" >/dev/null
write_jsonl "$repo_generation" "$UUID_C"
printf 'TOKEN=%s\n' "$sanitize_secret" >> "$repo_generation/.specstory/history/session.md"
generation_tree_before="$(git -C "$repo_generation" write-tree)"
generation_index="$(git -C "$repo_generation" rev-parse --git-path index)"
case "$generation_index" in /*) ;; *) generation_index="$repo_generation/$generation_index" ;; esac
export FAKE_GITLEAKS_STATE="$BASE/generation-scanner-state"
export FAKE_GITLEAKS_MUTATE_ON_CALL=1
STAGE_PATH="$SANITIZE_BIN:$SYSTEM_PATH"
run_stage "$repo_generation" --session-only --session-id "$UUID_C" --no-plan \
  --sanitize-index --materialize-sanitized
generation_worktree="$(<"$repo_generation/.specstory/history/session.md")"
generation_temp="$(find "$(dirname "$generation_index")" -maxdepth 1 \
  -name "$(basename "$generation_index").agent-history.*" -print -quit)"
if [ "$LAST_RC" = "5" ] && \
   [ "$(git -C "$repo_generation" write-tree)" = "$generation_tree_before" ] && \
   ! git -C "$repo_generation" ls-files --error-unmatch -- \
     .specstory/history/session.md >/dev/null 2>&1 && \
   contains "$generation_worktree" "$sanitize_secret" && \
   contains "$generation_worktree" 'writer-generation-changed' && \
   ! contains "$generation_worktree" '[REDACTED:fixture-rule]' && \
   [ ! -e "$generation_index.lock" ] && [ -z "$generation_temp" ]; then
  pass "changed live generation aborts before materialization or index publication"
else
  fail "changed live generation aborts before materialization or index publication"
fi
unset FAKE_GITLEAKS_STATE FAKE_GITLEAKS_MUTATE_ON_CALL

# Deterministic checkout barriers exercise both sides of the inode handoff.
# The wrapper never prints command arguments or file content.
materialize_barrier_bin="$BASE/materialize-barrier-bin"
mkdir -p "$materialize_barrier_bin"
cat > "$materialize_barrier_bin/git" <<'SH'
#!/usr/bin/env bash
if [ "${1:-}" = checkout-index ]; then
  case "${MATERIALIZE_BARRIER_MODE:-}" in
    before)
      : > "$MATERIALIZE_SYNC/ready"
      while [ ! -e "$MATERIALIZE_SYNC/release" ]; do sleep 0.02; done
      ;;
    after)
      "$REAL_GIT" "$@"
      checkout_rc=$?
      : > "$MATERIALIZE_SYNC/ready"
      while [ ! -e "$MATERIALIZE_SYNC/release" ]; do sleep 0.02; done
      exit "$checkout_rc"
      ;;
  esac
fi
exec "$REAL_GIT" "$@"
SH
chmod +x "$materialize_barrier_bin/git"
real_git="$(command -v git)"

# Append after every pre-checkout hash. The hard-link backup follows the old
# inode, so the append is detected after checkout and atomically restored. A
# second selected path proves unaffected siblings roll back too.
repo_before_checkout="$(make_repo 'append after proven hash')"
printf '%s\n' changed >> "$repo_before_checkout/feature.txt"
git -C "$repo_before_checkout" add feature.txt
before_transcript="$(write_transcript "$repo_before_checkout" 'session.md' "$UUID_B")"
before_plan="$(write_plan "$repo_before_checkout" 'plan.md')"
cp "$before_plan" "$BASE/before-plan-copy"
write_jsonl "$repo_before_checkout" "$UUID_B"
printf 'TOKEN=%s\n' "$sanitize_secret" >> "$before_transcript"
before_checkout_tree="$(git -C "$repo_before_checkout" write-tree)"
before_sync="$BASE/materialize-before-sync"
mkdir -p "$before_sync"
(
  cd "$repo_before_checkout" || exit 90
  HOME="$FAKE_HOME" PATH="$materialize_barrier_bin:$SANITIZE_BIN:$SYSTEM_PATH" \
    REAL_GIT="$real_git" MATERIALIZE_SYNC="$before_sync" \
    MATERIALIZE_BARRIER_MODE=before \
    FAKE_GITLEAKS_FILE='.specstory/history/session.md' \
    FAKE_GITLEAKS_SECRET="$sanitize_secret" \
    "$BASH" "$STAGE" --session-only --session-id "$UUID_B" \
      --plan '.claude/plans/plan.md' --sanitize-index --materialize-sanitized
) >"$BASE/materialize-before-out" 2>"$BASE/materialize-before-err" &
before_pid=$!
before_wait=0
while [ ! -e "$before_sync/ready" ] && [ "$before_wait" -lt 3000 ]; do
  sleep 0.02
  before_wait=$((before_wait + 1))
done
before_reached=0
[ -e "$before_sync/ready" ] && before_reached=1
printf '%s\n' 'writer-after-proven-hash' >> "$before_transcript"
: > "$before_sync/release"
wait "$before_pid"
before_rc=$?
before_content="$(<"$before_transcript")"
before_backups="$(find "$repo_before_checkout" -name '.agent-history-backup.*' -print -quit)"
before_recoveries="$(find "$repo_before_checkout" -name '.agent-history-recovery.*' -print -quit)"
if [ "$before_reached" = "1" ] && [ "$before_rc" = "5" ] && \
   [ "$(git -C "$repo_before_checkout" write-tree)" = "$before_checkout_tree" ] && \
   ! git -C "$repo_before_checkout" ls-files --error-unmatch -- \
     .specstory/history/session.md >/dev/null 2>&1 && \
   contains "$before_content" "$sanitize_secret" && \
   contains "$before_content" 'writer-after-proven-hash' && \
   ! contains "$before_content" '[REDACTED:fixture-rule]' && \
   cmp -s "$before_plan" "$BASE/before-plan-copy" && \
   [ -z "$before_backups" ] && [ -z "$before_recoveries" ]; then
  pass "append after pre-checkout hash is restored without sibling loss"
else
  fail "append after pre-checkout hash is restored without sibling loss"
fi

# Append to the replacement pathname after checkout. The old backup remains
# clean, so rollback preserves the writer-modified new path and removes only the
# owned backup; the candidate index is still discarded.
repo_after_checkout="$(make_repo 'append to replaced path')"
printf '%s\n' changed >> "$repo_after_checkout/feature.txt"
git -C "$repo_after_checkout" add feature.txt
after_transcript="$(write_transcript "$repo_after_checkout" 'session.md' "$UUID_C")"
write_jsonl "$repo_after_checkout" "$UUID_C"
printf 'TOKEN=%s\n' "$sanitize_secret" >> "$after_transcript"
after_checkout_tree="$(git -C "$repo_after_checkout" write-tree)"
after_sync="$BASE/materialize-after-sync"
mkdir -p "$after_sync"
(
  cd "$repo_after_checkout" || exit 90
  HOME="$FAKE_HOME" PATH="$materialize_barrier_bin:$SANITIZE_BIN:$SYSTEM_PATH" \
    REAL_GIT="$real_git" MATERIALIZE_SYNC="$after_sync" \
    MATERIALIZE_BARRIER_MODE=after \
    FAKE_GITLEAKS_FILE='.specstory/history/session.md' \
    FAKE_GITLEAKS_SECRET="$sanitize_secret" \
    "$BASH" "$STAGE" --session-only --session-id "$UUID_C" --no-plan \
      --sanitize-index --materialize-sanitized
) >"$BASE/materialize-after-out" 2>"$BASE/materialize-after-err" &
after_pid=$!
after_wait=0
while [ ! -e "$after_sync/ready" ] && [ "$after_wait" -lt 3000 ]; do
  sleep 0.02
  after_wait=$((after_wait + 1))
done
after_reached=0
[ -e "$after_sync/ready" ] && after_reached=1
printf '%s\n' 'writer-on-replaced-path' >> "$after_transcript"
: > "$after_sync/release"
wait "$after_pid"
after_rc=$?
after_content="$(<"$after_transcript")"
after_backups="$(find "$repo_after_checkout" -name '.agent-history-backup.*' -print -quit)"
after_recoveries="$(find "$repo_after_checkout" -name '.agent-history-recovery.*' -print -quit)"
if [ "$after_reached" = "1" ] && [ "$after_rc" = "5" ] && \
   [ "$(git -C "$repo_after_checkout" write-tree)" = "$after_checkout_tree" ] && \
   ! git -C "$repo_after_checkout" ls-files --error-unmatch -- \
     .specstory/history/session.md >/dev/null 2>&1 && \
   contains "$after_content" '[REDACTED:fixture-rule]' && \
   contains "$after_content" 'writer-on-replaced-path' && \
   ! contains "$after_content" "$sanitize_secret" && \
   [ -z "$after_backups" ] && [ -z "$after_recoveries" ]; then
  pass "append to replaced path is preserved and index publication aborts"
else
  fail "append to replaced path is preserved and index publication aborts"
fi

# Materialization goes through Git's smudge filter, while the safety comparison
# hashes the live file through the corresponding clean filter.
repo_filter="$(make_repo 'sanitize with git filters')"
clean_filter="$BASE/clean-filter.py"
smudge_filter="$BASE/smudge-filter.py"
cat > "$clean_filter" <<'PY'
import sys
value = sys.stdin.buffer.read()
sys.stdout.buffer.write(value.replace(b"WORKTREE-MARKER", b"INDEX-MARKER"))
PY
cat > "$smudge_filter" <<'PY'
import sys
value = sys.stdin.buffer.read()
sys.stdout.buffer.write(value.replace(b"INDEX-MARKER", b"WORKTREE-MARKER"))
PY
git -C "$repo_filter" config filter.fixture.clean "python3 $clean_filter"
git -C "$repo_filter" config filter.fixture.smudge "python3 $smudge_filter"
git -C "$repo_filter" config filter.fixture.required true
printf '%s\n' '.specstory/history/*.md filter=fixture' > "$repo_filter/.gitattributes"
git -C "$repo_filter" add .gitattributes
git -C "$repo_filter" -c core.hooksPath=/dev/null -c user.name=test \
  -c user.email=test@example.com commit -q -m attributes
printf '%s\n' changed >> "$repo_filter/feature.txt"
git -C "$repo_filter" add feature.txt
write_transcript "$repo_filter" 'session.md' "$UUID_A" >/dev/null
write_jsonl "$repo_filter" "$UUID_A"
printf 'WORKTREE-MARKER=%s\n' "$sanitize_secret" >> \
  "$repo_filter/.specstory/history/session.md"
unset FAKE_GITLEAKS_STATE FAKE_GITLEAKS_MUTATE_ON_CALL
STAGE_PATH="$SANITIZE_BIN:$SYSTEM_PATH"
run_stage "$repo_filter" --session-only --session-id "$UUID_A" --no-plan \
  --sanitize-index --materialize-sanitized
filter_index="$(git -C "$repo_filter" show :.specstory/history/session.md)"
filter_worktree="$(<"$repo_filter/.specstory/history/session.md")"
filter_live_oid="$(cd "$repo_filter" && git hash-object \
  --path=.specstory/history/session.md -- .specstory/history/session.md)"
filter_index_oid="$(git -C "$repo_filter" ls-files -s -- \
  .specstory/history/session.md | cut -d' ' -f2)"
if [ "$LAST_RC" = "10" ] && contains "$filter_index" 'INDEX-MARKER=' && \
   contains "$filter_worktree" 'WORKTREE-MARKER=' && \
   contains "$filter_index" '[REDACTED:fixture-rule]' && \
   contains "$filter_worktree" '[REDACTED:fixture-rule]' && \
   [ "$filter_live_oid" = "$filter_index_oid" ]; then
  pass "sanitized materialization honors clean and smudge filter semantics"
else
  fail "sanitized materialization honors clean and smudge filter semantics"
fi
unset FAKE_GITLEAKS_FILE FAKE_GITLEAKS_SECRET REAL_GIT GIT_ADD_LOG
STAGE_PATH=""

# Hold the real index lock while the alternate index is validated and updated.
# A concurrent normal Git writer must fail rather than removing staged code
# between the feature guard and artifact publication.
repo_race="$(make_repo 'index transaction race')"
printf '%s\n' changed >> "$repo_race/feature.txt"
git -C "$repo_race" add feature.txt
write_transcript "$repo_race" 'session.md' "$UUID_C" >/dev/null
write_plan "$repo_race" 'plan.md' >/dev/null
write_jsonl "$repo_race" "$UUID_C"
race_bin="$BASE/race-bin"
race_sync="$BASE/race-sync"
mkdir -p "$race_bin" "$race_sync"
real_git="$(command -v git)"
cat > "$race_bin/git" <<'SH'
#!/usr/bin/env bash
if [ -n "${GIT_INDEX_FILE:-}" ] && [ ! -e "$RACE_SYNC/inside-transaction" ]; then
  : > "$RACE_SYNC/inside-transaction"
  while [ ! -e "$RACE_SYNC/release" ]; do sleep 0.02; done
fi
exec "$REAL_GIT" "$@"
SH
chmod +x "$race_bin/git"
index_path="$(HOME="$FAKE_HOME" git -C "$repo_race" rev-parse --git-path index)"
case "$index_path" in /*) ;; *) index_path="$repo_race/$index_path" ;; esac
(
  cd "$repo_race" || exit 1
  PATH="$race_bin:$SYSTEM_PATH" REAL_GIT="$real_git" RACE_SYNC="$race_sync" HOME="$FAKE_HOME" \
    "$BASH" "$STAGE" --session-only --session-id "$UUID_C" --plan '.claude/plans/plan.md'
) >"$BASE/race-stage-out" 2>"$BASE/race-stage-err" &
race_pid=$!
race_wait=0
while [ ! -e "$race_sync/inside-transaction" ] && [ "$race_wait" -lt 500 ]; do
  sleep 0.02
  race_wait=$((race_wait + 1))
done
git -C "$repo_race" restore --staged feature.txt >/dev/null 2>"$BASE/race-writer-err"
concurrent_rc=$?
: > "$race_sync/release"
wait "$race_pid"
race_stage_rc=$?
race_names="$(staged_names "$repo_race")"
leftover_temp="$(find "$(dirname "$index_path")" -maxdepth 1 -name "$(basename "$index_path").agent-history.*" -print -quit)"
if [ "$race_stage_rc" = "0" ] && [ "$concurrent_rc" != "0" ] && \
   contains "$race_names" 'feature.txt' && contains "$race_names" '.specstory/history/session.md' && \
   contains "$race_names" '.claude/plans/plan.md' && [ ! -e "$index_path.lock" ] && \
   [ -z "$leftover_temp" ]; then
  pass "index lock prevents concurrent writer across staged guard and exact add"
else
  fail "index lock prevents concurrent writer across staged guard and exact add"
fi


# Broad mode must stage unstaged deletion and rename pairs from one porcelain
# snapshot, including the rename origin needed to remove the old path.
repo_status="$(make_repo 'broad deletion rename states')"
mkdir -p "$repo_status/.specstory/history" "$repo_status/.claude/plans"
printf '# delete me\n' > "$repo_status/.specstory/history/deleted.md"
printf '# rename me\n' > "$repo_status/.claude/plans/old-name.md"
git -C "$repo_status" add .specstory/history/deleted.md .claude/plans/old-name.md
git -C "$repo_status" -c core.hooksPath=/dev/null -c user.name=test -c user.email=test@example.com \
  commit -q -m artifacts
printf '%s\n' changed >> "$repo_status/feature.txt"
git -C "$repo_status" add feature.txt
rm "$repo_status/.specstory/history/deleted.md"
mv "$repo_status/.claude/plans/old-name.md" "$repo_status/.claude/plans/new-name.md"
run_stage "$repo_status"
name_status="$(git -C "$repo_status" diff --cached --name-status --find-renames)"
if [ "$LAST_RC" = "0" ] && contains "$name_status" $'D\t.specstory/history/deleted.md' && \
   contains "$name_status" $'R100\t.claude/plans/old-name.md\t.claude/plans/new-name.md'; then
  pass "broad snapshot stages deleted and paired renamed artifacts"
else
  fail "broad snapshot stages deleted and paired renamed artifacts"
fi

# A staged artifact-only rename plus an unstaged modification produces an RM
# porcelain pair. Its origin is metadata, not a fake non-artifact feature path.
repo_origin="$(make_repo 'rename origin guard')"
mkdir -p "$repo_origin/.claude/plans"
printf '# original\n' > "$repo_origin/.claude/plans/old.md"
git -C "$repo_origin" add .claude/plans/old.md
git -C "$repo_origin" -c core.hooksPath=/dev/null -c user.name=test -c user.email=test@example.com \
  commit -q -m artifact
git -C "$repo_origin" mv .claude/plans/old.md .claude/plans/new.md
printf '%s\n' changed >> "$repo_origin/.claude/plans/new.md"
before_tree="$(git -C "$repo_origin" write-tree)"
run_stage "$repo_origin"
if [ "$LAST_RC" = "4" ] && [ "$(git -C "$repo_origin" write-tree)" = "$before_tree" ]; then
  pass "rename origin cannot bypass staged non-artifact guard"
else
  fail "rename origin cannot bypass staged non-artifact guard"
fi

# Neither broad nor exact mode may use git add to collapse an unmerged artifact
# into a stage-0 blob containing conflict markers.
repo_artifact_conflict="$(make_repo 'unmerged transcript')"
conflict_transcript="$(write_transcript "$repo_artifact_conflict" 'conflict.md' "$UUID_A")"
printf '%s\n' base >> "$conflict_transcript"
git -C "$repo_artifact_conflict" add .specstory/history/conflict.md
git -C "$repo_artifact_conflict" -c core.hooksPath=/dev/null -c user.name=test -c user.email=test@example.com \
  commit -q -m transcript
git -C "$repo_artifact_conflict" checkout -q -b conflict-side
write_transcript "$repo_artifact_conflict" 'conflict.md' "$UUID_A" >/dev/null
printf '%s\n' side >> "$conflict_transcript"
git -C "$repo_artifact_conflict" add .specstory/history/conflict.md
git -C "$repo_artifact_conflict" -c core.hooksPath=/dev/null -c user.name=test -c user.email=test@example.com \
  commit -q -m side
git -C "$repo_artifact_conflict" checkout -q main
write_transcript "$repo_artifact_conflict" 'conflict.md' "$UUID_A" >/dev/null
printf '%s\n' main >> "$conflict_transcript"
git -C "$repo_artifact_conflict" add .specstory/history/conflict.md
git -C "$repo_artifact_conflict" -c core.hooksPath=/dev/null -c user.name=test -c user.email=test@example.com \
  commit -q -m main
git -C "$repo_artifact_conflict" -c core.hooksPath=/dev/null merge conflict-side >/dev/null 2>&1
merge_rc=$?
write_jsonl "$repo_artifact_conflict" "$UUID_A"
conflict_index_before="$(git -C "$repo_artifact_conflict" ls-files -s)"
run_stage "$repo_artifact_conflict"
broad_conflict_rc="$LAST_RC"
run_stage "$repo_artifact_conflict" --session-only --session-id "$UUID_A" --no-plan
exact_conflict_rc="$LAST_RC"
conflict_index_after="$(git -C "$repo_artifact_conflict" ls-files -s)"
if [ "$merge_rc" != "0" ] && [ "$broad_conflict_rc" = "5" ] && \
   [ "$exact_conflict_rc" = "5" ] && [ "$conflict_index_before" = "$conflict_index_after" ] && \
   [ -n "$(git -C "$repo_artifact_conflict" ls-files -u -- .specstory/history/conflict.md)" ]; then
  pass "unmerged transcript is rejected without resolving the index"
else
  fail "unmerged transcript is rejected without resolving the index"
fi

# A code conflict is not a staged feature diff. It cannot authorize staging an
# otherwise addable artifact.
repo_code_conflict="$(make_repo 'unmerged code guard')"
git -C "$repo_code_conflict" checkout -q -b code-side
printf '%s\n' side > "$repo_code_conflict/feature.txt"
git -C "$repo_code_conflict" add feature.txt
git -C "$repo_code_conflict" -c core.hooksPath=/dev/null -c user.name=test -c user.email=test@example.com \
  commit -q -m side
git -C "$repo_code_conflict" checkout -q main
printf '%s\n' main > "$repo_code_conflict/feature.txt"
git -C "$repo_code_conflict" add feature.txt
git -C "$repo_code_conflict" -c core.hooksPath=/dev/null -c user.name=test -c user.email=test@example.com \
  commit -q -m main
git -C "$repo_code_conflict" -c core.hooksPath=/dev/null merge code-side >/dev/null 2>&1
mkdir -p "$repo_code_conflict/.claude/plans"
printf '# dirty plan\n' > "$repo_code_conflict/.claude/plans/dirty.md"
code_conflict_before="$(git -C "$repo_code_conflict" ls-files -s)"
run_stage "$repo_code_conflict"
if [ "$LAST_RC" = "4" ] && [ "$(git -C "$repo_code_conflict" ls-files -s)" = "$code_conflict_before" ] && \
   [ -n "$(git -C "$repo_code_conflict" ls-files -u -- feature.txt)" ] && \
   ! git -C "$repo_code_conflict" ls-files --error-unmatch -- .claude/plans/dirty.md >/dev/null 2>&1; then
  pass "unmerged code does not satisfy the staged feature guard"
else
  fail "unmerged code does not satisfy the staged feature guard"
fi

# Historical broad mode remains available and stages every dirty Markdown
# artifact under configured directories without requiring exact headers.
repo_broad="$(make_repo 'broad compatibility')"
printf '%s\n' changed >> "$repo_broad/feature.txt"
git -C "$repo_broad" add feature.txt
mkdir -p "$repo_broad/.specstory/history" "$repo_broad/.claude/plans" "$repo_broad/.cursor/rules"
printf '# legacy\n' > "$repo_broad/.specstory/history/legacy.md"
printf '# plan\n' > "$repo_broad/.claude/plans/all.md"
printf '# rule\n' > "$repo_broad/.cursor/rules/rule.md"
run_stage "$repo_broad"
names="$(staged_names "$repo_broad")"
if [ "$LAST_RC" = "0" ] && [ "$(staged_count "$repo_broad")" = "4" ] && \
   contains "$names" '.specstory/history/legacy.md' && \
   contains "$names" '.claude/plans/all.md' && contains "$names" '.cursor/rules/rule.md'; then
  pass "broad branch-wide compatibility mode stages all dirty artifacts"
else
  fail "broad branch-wide compatibility mode stages all dirty artifacts"
fi

printf '\n== bootstrap exact hook ==\n'

# Install with a local no-op pre-commit executable so the test never downloads.
fake_bin="$BASE/bin"
mkdir -p "$fake_bin"
printf '%s\n' '#!/usr/bin/env sh' 'exit 0' > "$fake_bin/pre-commit"
chmod +x "$fake_bin/pre-commit"

failing_bin="$BASE/failing-bin"
mkdir -p "$failing_bin"
printf '%s\n' '#!/usr/bin/env sh' 'exit 42' > "$failing_bin/pre-commit"
chmod +x "$failing_bin/pre-commit"
repo_install_failure="$(make_repo 'pre-commit install failure')"
(cd "$repo_install_failure" && HOME="$FAKE_HOME" PATH="$failing_bin:$SYSTEM_PATH" \
  "$BASH" "$BOOTSTRAP") >"$BASE/install-failure-out" 2>"$BASE/install-failure-err"
install_failure_rc=$?
install_failure_output="$(<"$BASE/install-failure-out")$(<"$BASE/install-failure-err")"
if [ "$install_failure_rc" = "42" ] && ! contains "$install_failure_output" 'Bootstrap complete'; then
  pass "bootstrap propagates pre-commit install failure"
else
  fail "bootstrap propagates pre-commit install failure"
fi

repo_hook="$(make_repo 'hook behavior')"
bootstrap_out="$BASE/bootstrap-out"
bootstrap_err="$BASE/bootstrap-err"
(cd "$repo_hook" && HOME="$FAKE_HOME" PATH="$fake_bin:$SYSTEM_PATH" \
  "$BASH" "$BOOTSTRAP" --install-hook) >"$bootstrap_out" 2>"$bootstrap_err"
bootstrap_rc=$?
hook_path="$(HOME="$FAKE_HOME" git -C "$repo_hook" rev-parse --git-path hooks/prepare-commit-msg)"
case "$hook_path" in /*) ;; *) hook_path="$repo_hook/$hook_path" ;; esac

before_tree="$(git -C "$repo_hook" write-tree)"
(cd "$repo_hook" && HOME="$FAKE_HOME" PATH="$SYSTEM_PATH" \
  AGENT_HISTORY_SESSION_ID='' AGENT_HISTORY_SPECSTORY_PATH='' \
  AGENT_HISTORY_PLAN='' AGENT_HISTORY_NO_PLAN='' AGENT_HISTORY_NO_SPECSTORY='' \
  "$BASH" "$hook_path" message.txt) >"$BASE/hook-out" 2>"$BASE/hook-err"
hook_rc=$?
hook_err="$(<"$BASE/hook-err")"
if [ "$bootstrap_rc" = "0" ] && [ "$hook_rc" = "0" ] && \
   contains "$hook_err" 'skipping staged-artifact validation' && \
   [ "$(git -C "$repo_hook" write-tree)" = "$before_tree" ]; then
  pass "validation hook visibly no-ops without AGENT_HISTORY identity"
else
  fail "validation hook visibly no-ops without AGENT_HISTORY identity"
fi

write_transcript "$repo_hook" 'hook session.md' "$UUID_C" >/dev/null
write_plan "$repo_hook" 'hook plan.md' >/dev/null
write_jsonl "$repo_hook" "$UUID_C"
# Identity without a plan policy is a real error and must not be swallowed.
index_before_error="$(git -C "$repo_hook" write-tree)"
(cd "$repo_hook" && HOME="$FAKE_HOME" PATH="$SYSTEM_PATH" AGENT_HISTORY_SESSION_ID="$UUID_C" \
  "$BASH" "$hook_path" message.txt) >/dev/null 2>"$BASE/hook-error"
hook_error_rc=$?
if [ "$hook_error_rc" = "1" ] && [ "$(git -C "$repo_hook" write-tree)" = "$index_before_error" ]; then
  pass "validation hook propagates missing plan-policy failure"
else
  fail "validation hook propagates missing plan-policy failure"
fi

# A normal commit with only feature code staged must fail validation without
# changing the real index. The hook prints the exact staging command.
printf '%s\n' changed >> "$repo_hook/feature.txt"
git -C "$repo_hook" add feature.txt
commit_count_before="$(git -C "$repo_hook" rev-list --count HEAD)"
index_before_commit="$(git -C "$repo_hook" ls-files -s)"
(cd "$repo_hook" && HOME="$FAKE_HOME" PATH="$SYSTEM_PATH" AGENT_HISTORY_SESSION_ID="$UUID_C" \
  AGENT_HISTORY_SPECSTORY_PATH='.specstory/history/hook session.md' \
  AGENT_HISTORY_PLAN='.claude/plans/hook plan.md' \
  git -c user.name=test -c user.email=test@example.com commit -m 'test: validation hook') \
  >"$BASE/commit-missing-out" 2>"$BASE/commit-missing-err"
missing_commit_rc=$?
missing_commit_err="$(<"$BASE/commit-missing-err")"
if [ "$missing_commit_rc" != "0" ] && \
   [ "$(git -C "$repo_hook" rev-list --count HEAD)" = "$commit_count_before" ] && \
   [ "$(git -C "$repo_hook" ls-files -s)" = "$index_before_commit" ] && \
   contains "$missing_commit_err" 'stage feature paths, then run this exact staging command'; then
  pass "normal commit rejects unstaged artifacts without index mutation"
else
  fail "normal commit rejects unstaged artifacts without index mutation"
fi

run_stage "$repo_hook" --session-only --session-id "$UUID_C" \
  --specstory-path '.specstory/history/hook session.md' \
  --plan '.claude/plans/hook plan.md'
(cd "$repo_hook" && HOME="$FAKE_HOME" PATH="$SYSTEM_PATH" AGENT_HISTORY_SESSION_ID="$UUID_C" \
  AGENT_HISTORY_SPECSTORY_PATH='.specstory/history/hook session.md' \
  AGENT_HISTORY_PLAN='.claude/plans/hook plan.md' \
  git -c user.name=test -c user.email=test@example.com commit -m 'test: validation hook') \
  >"$BASE/commit-normal-out" 2>"$BASE/commit-normal-err"
normal_commit_rc=$?
committed_names="$(git -C "$repo_hook" show --format= --name-only HEAD)"
if [ "$normal_commit_rc" = "0" ] && contains "$committed_names" 'feature.txt' && \
   contains "$committed_names" '.specstory/history/hook session.md' && \
   contains "$committed_names" '.claude/plans/hook plan.md'; then
  pass "normal commit succeeds after explicit exact staging"
else
  fail "normal commit succeeds after explicit exact staging"
fi

# `commit -a` prepares a temporary index with tracked code but excludes untracked
# artifacts. Validation fails and the real index remains untouched.
repo_commit_a="$(make_repo 'commit a validation')"
(cd "$repo_commit_a" && HOME="$FAKE_HOME" PATH="$fake_bin:$SYSTEM_PATH" \
  "$BASH" "$BOOTSTRAP" --install-hook) >/dev/null 2>&1
write_transcript "$repo_commit_a" 'session.md' "$UUID_A" >/dev/null
write_plan "$repo_commit_a" 'plan.md' >/dev/null
write_jsonl "$repo_commit_a" "$UUID_A"
printf '%s\n' changed >> "$repo_commit_a/feature.txt"
commit_a_index_before="$(git -C "$repo_commit_a" ls-files -s)"
commit_a_count="$(git -C "$repo_commit_a" rev-list --count HEAD)"
(cd "$repo_commit_a" && HOME="$FAKE_HOME" PATH="$SYSTEM_PATH" AGENT_HISTORY_SESSION_ID="$UUID_A" \
  AGENT_HISTORY_PLAN='.claude/plans/plan.md' \
  git -c user.name=test -c user.email=test@example.com commit -a -m 'test: commit a') \
  >"$BASE/commit-a-out" 2>"$BASE/commit-a-err"
commit_a_rc=$?
if [ "$commit_a_rc" != "0" ] && [ "$(git -C "$repo_commit_a" ls-files -s)" = "$commit_a_index_before" ] && \
   [ "$(git -C "$repo_commit_a" rev-list --count HEAD)" = "$commit_a_count" ]; then
  pass "commit -a exclusion fails validation without touching real index"
else
  fail "commit -a exclusion fails validation without touching real index"
fi

# `commit --only` can exclude artifacts that are staged in the real index. The
# hook validates Git's temporary commit index, fails, and leaves real staging
# intact; a subsequent normal commit succeeds without a loop.
repo_commit_only="$(make_repo 'commit only validation')"
(cd "$repo_commit_only" && HOME="$FAKE_HOME" PATH="$fake_bin:$SYSTEM_PATH" \
  "$BASH" "$BOOTSTRAP" --install-hook) >/dev/null 2>&1
write_transcript "$repo_commit_only" 'session.md' "$UUID_B" >/dev/null
write_plan "$repo_commit_only" 'plan.md' >/dev/null
write_jsonl "$repo_commit_only" "$UUID_B"
printf '%s\n' changed >> "$repo_commit_only/feature.txt"
git -C "$repo_commit_only" add feature.txt
run_stage "$repo_commit_only" --session-only --session-id "$UUID_B" \
  --plan '.claude/plans/plan.md'
only_index_before="$(git -C "$repo_commit_only" ls-files -s)"
(cd "$repo_commit_only" && HOME="$FAKE_HOME" PATH="$SYSTEM_PATH" AGENT_HISTORY_SESSION_ID="$UUID_B" \
  AGENT_HISTORY_PLAN='.claude/plans/plan.md' \
  git -c user.name=test -c user.email=test@example.com commit --only feature.txt -m 'test: commit only') \
  >"$BASE/commit-only-out" 2>"$BASE/commit-only-err"
commit_only_rc=$?
if [ "$commit_only_rc" != "0" ] && \
   [ "$(git -C "$repo_commit_only" ls-files -s)" = "$only_index_before" ]; then
  pass "commit --only exclusion fails against temporary index without mutation"
else
  fail "commit --only exclusion fails against temporary index without mutation"
fi
(cd "$repo_commit_only" && HOME="$FAKE_HOME" PATH="$SYSTEM_PATH" AGENT_HISTORY_SESSION_ID="$UUID_B" \
  AGENT_HISTORY_PLAN='.claude/plans/plan.md' \
  git -c user.name=test -c user.email=test@example.com commit -m 'test: normal after only') \
  >"$BASE/commit-after-only-out" 2>"$BASE/commit-after-only-err"
after_only_rc=$?
if [ "$after_only_rc" = "0" ]; then
  pass "normal commit succeeds after commit --only validation failure"
else
  fail "normal commit succeeds after commit --only validation failure"
fi

# Relative .git/hooks works in the primary checkout but becomes non-traversable
# in a linked worktree where .git is a file. Prove the asymmetry with real
# commits, then require bootstrap to refuse both checkouts.
repo_relative_hooks="$(make_repo 'relative hooks primary')"
linked_relative_hooks="$BASE/relative hooks linked"
git -C "$repo_relative_hooks" worktree add -q -b relative-linked "$linked_relative_hooks"
git -C "$repo_relative_hooks" config core.hooksPath .git/hooks
relative_marker="$BASE/relative-hook-hits"
cat > "$repo_relative_hooks/.git/hooks/prepare-commit-msg" <<HOOK
#!/usr/bin/env sh
printf '%s\n' hit >> "$relative_marker"
HOOK
chmod +x "$repo_relative_hooks/.git/hooks/prepare-commit-msg"
printf '%s\n' primary >> "$repo_relative_hooks/feature.txt"
git -C "$repo_relative_hooks" add feature.txt
git -C "$repo_relative_hooks" -c user.name=test -c user.email=test@example.com commit -q -m primary
primary_relative_commit_rc=$?
printf '%s\n' linked >> "$linked_relative_hooks/feature.txt"
git -C "$linked_relative_hooks" add feature.txt
git -C "$linked_relative_hooks" -c user.name=test -c user.email=test@example.com commit -q -m linked
linked_relative_commit_rc=$?
relative_hits="$(wc -l < "$relative_marker" | tr -d ' ')"
(cd "$repo_relative_hooks" && HOME="$FAKE_HOME" PATH="$fake_bin:$SYSTEM_PATH" \
  "$BASH" "$BOOTSTRAP" --install-hook --dry-run) >/dev/null 2>&1
primary_bootstrap_rc=$?
(cd "$linked_relative_hooks" && HOME="$FAKE_HOME" PATH="$fake_bin:$SYSTEM_PATH" \
  "$BASH" "$BOOTSTRAP" --install-hook --dry-run) >/dev/null 2>&1
linked_bootstrap_rc=$?
if [ "$primary_relative_commit_rc" = "0" ] && [ "$linked_relative_commit_rc" = "0" ] && \
   [ "$relative_hits" = "1" ] && [ "$primary_bootstrap_rc" = "6" ] && \
   [ "$linked_bootstrap_rc" = "6" ]; then
  pass "relative core.hooksPath is refused after primary/linked commit probe"
else
  fail "relative core.hooksPath is refused after primary/linked commit probe"
fi

repo_empty_hooks="$(make_repo 'empty hooks path')"
git -C "$repo_empty_hooks" config core.hooksPath ''
(cd "$repo_empty_hooks" && HOME="$FAKE_HOME" PATH="$fake_bin:$SYSTEM_PATH" \
  "$BASH" "$BOOTSTRAP" --install-hook --dry-run) \
  >"$BASE/empty-hooks-out" 2>"$BASE/empty-hooks-err"
empty_hooks_rc=$?
empty_hooks_output="$(<"$BASE/empty-hooks-out")$(<"$BASE/empty-hooks-err")"
if [ "$empty_hooks_rc" = "6" ] && ! contains "$empty_hooks_output" '/prepare-commit-msg' && \
   [ ! -e "$repo_empty_hooks/.pre-commit-config.yaml" ]; then
  pass "configured-empty core.hooksPath fails before constructing a root hook path"
else
  fail "configured-empty core.hooksPath fails before constructing a root hook path"
fi

repo_global="$(make_repo 'global hooks path')"
git -C "$repo_global" config core.hooksPath .githooks
(cd "$repo_global" && HOME="$FAKE_HOME" PATH="$fake_bin:$SYSTEM_PATH" \
  "$BASH" "$BOOTSTRAP" --install-hook --dry-run) >/dev/null 2>&1
global_rc=$?
if [ "$global_rc" = "6" ] && [ ! -e "$repo_global/.pre-commit-config.yaml" ]; then
  pass "global core.hooksPath refusal remains pre-write"
else
  fail "global core.hooksPath refusal remains pre-write"
fi

printf 'pass: %d\nfail: %d\n' "$PASS_COUNT" "$FAIL_COUNT"
[ "$FAIL_COUNT" = "0" ]
