#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = [
#   "mlflow>=2.18",
#   "pandas>=2.0",
# ]
# ///
"""tail-runs.sh — Query MLflow runs and emit them as JSON or CSV to stdout.

Wraps `mlflow.search_runs` for terminal use. Designed for an LLM caller
(structured stdout, prose to stderr).

Run `tail-runs.sh --help` for the full flag list (auto-generated by argparse).

Examples:
    tail-runs.sh --experiment my-project
    tail-runs.sh --experiment my-project --top-n 5 --sort-by metrics.val_acc
    tail-runs.sh --experiment my-project --format csv | column -t -s,
    tail-runs.sh --tracking-uri sqlite:///mlflow.db --experiment my-project
"""

from __future__ import annotations

import argparse
import json
import os
import sys

import mlflow
import pandas as pd


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--experiment",
        required=True,
        help="Experiment name to search.",
    )
    p.add_argument(
        "--tracking-uri",
        default=os.environ.get("MLFLOW_TRACKING_URI"),
        help="MLflow tracking URI (default: $MLFLOW_TRACKING_URI).",
    )
    p.add_argument(
        "--top-n",
        type=int,
        default=20,
        help="Max runs to return (default: 20).",
    )
    p.add_argument(
        "--sort-by",
        default="start_time",
        help="Column to sort by, descending. Examples: start_time, metrics.val_acc, params.lr.",
    )
    p.add_argument(
        "--filter",
        default="",
        help='MLflow filter string. Example: "metrics.val_acc > 0.9".',
    )
    p.add_argument(
        "--format",
        choices=["json", "csv"],
        default="json",
        help="Output format on stdout (default: json).",
    )
    p.add_argument(
        "--columns",
        default="",
        help="Comma-separated column subset (default: all columns from search_runs).",
    )
    return p.parse_args()


def main() -> int:
    args = parse_args()

    if args.tracking_uri:
        mlflow.set_tracking_uri(args.tracking_uri)
        print(f"tracking_uri: {args.tracking_uri}", file=sys.stderr)
    else:
        print("warn: no --tracking-uri and no $MLFLOW_TRACKING_URI; using mlflow default",
              file=sys.stderr)

    try:
        df: pd.DataFrame = mlflow.search_runs(
            experiment_names=[args.experiment],
            filter_string=args.filter,
            max_results=args.top_n,
            order_by=[f"{args.sort_by} DESC"],
        )
    except Exception as exc:
        print(f"error: search_runs failed: {exc}", file=sys.stderr)
        return 3

    if df is None or df.empty:
        print(f"warn: no runs found for experiment '{args.experiment}'", file=sys.stderr)
        df = pd.DataFrame()

    if args.columns:
        cols = [c.strip() for c in args.columns.split(",") if c.strip()]
        missing = [c for c in cols if c not in df.columns]
        if missing:
            print(f"warn: missing columns ignored: {missing}", file=sys.stderr)
        cols = [c for c in cols if c in df.columns]
        df = df[cols] if cols else df

    if args.format == "csv":
        df.to_csv(sys.stdout, index=False)
    else:
        # JSON: emit a list of objects (more agent-friendly than DataFrame.to_json).
        records = json.loads(df.to_json(orient="records", date_format="iso"))
        print(json.dumps(records, indent=2, default=str))

    print(f"returned {len(df)} run(s)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
